;!q.done;q=n.next())q=q.value,c.push(new Vtd(b,new gm(q.left,q.top),l));else continue}d.push.apply(d,ka(k));a.D.C(36577,vHf(h))}else a.D.C(36578,vHf(h));e&&(d.push(yn(MT(a.F.getTableRange()))),f=xn(MT(ritz_api.TablesApi.getDataRange(a.F))).rect.top,c.push(new eCd(b.fc(),"r",f)));0<c.length&&a.H.C(new tHf(b,d,c));a=a.C;pHf(a.D);b=a.Fa("waffle-inline-assistant-sidebar-accepted-container");P(b,!0);P(a.F.Ka(),!1)}this.C.D=null;
this.C.H=null;this.R=[]};m.O2b=function(){this.Qa=!0;this.V.stop()};m.Q2b=function(){this.Qa=!1;this.L=null!=this.J?1E3:5E3;this.V.start(this.L)};
m.Lta=function(){this.Ta=this.Oa=this.Ea=!1;BHf(this);CHf(this);var a=SM(this.D);if(a){var b=[];if(this.C.D&&(b=AHf(this,this.C.D.C),!this.H))return;var c=this.C.getTableRange();if(c)var d=yGf(a,c.rect);else(d=yGf(a,a.F))&&(c=xn(MT(d.getTableRange())));var e=[],f=[],h=[],k=[],l=[],n=[],q=[];b=ja(b);for(var r=b.next();!r.done;r=b.next()){var w=r.value;r=xn(IV(w));this.R.push(r);switch(C(w,1)){case 7:var x=r.rect.left;if(ritz_api.RitzModelApi.getColumnType(a.fc(),x))continue;w=C(w,14);x=C(w,1);var F=
w.getPattern();F=wGf(this.D.F,x,F);w.setPattern(F);k.push(w);e.push(r);q[r.rect.left-c.rect.left]=w;break;case 8:w=C(w,15);l.push(w);f.push(r);break;case 9:w=C(w,16),n.push(w),h.push(r)}}DHf(this);a=[];b=[];if(c=JGf(this.xa,q,d,c))a=c.Uab,b=c.Sab;this.F&&(c=JDf(this.D.F),c.setValue(c.getValue()+1),this.F.initialize(d,e,k,b,a,f,l,h,n,this.C.C,this.C.F));c=this.C;c.Pa=d;c.V=e;c.Qa=k;c.Ia=b;c.Ea=a;c.xa=f;c.Za=l;c.ma=h;c.Ta=n}};
m.T2b=function(){var a=KV(this.O);if(a&&this.H){this.C.R=null!=this.J;var b=null!=this.F&&this.F.isVisible();this.C.La=b;this.F&&(b=xHf(this.F),this.C.Ca=b,b=this.F,b.Sf().isVisible()&&b.bL());this.La.set(this.H,this.C);null!=this.J&&this.Ia.C(36590);BHf(this);this.R=[];this.Ca||(this.V&&this.V.stop(),this.L=null);this.H=a;this.C=this.La.has(a)?this.La.get(a):new DGf(!1);a=this.xa;b=this.H;var c=this.C,d=this.R;b&&c&&a.D&&(a.D=b,a.C=c,IGf(a,d));if(this.C.R){if(a=cK(this.O))b=this.C.D?this.C.D.C:[],
this.J=QDf(a,this.O,this.$a,this.C.getTableRange(),b,this.C.C.length)}else if(this.C.La){a=this.C.Pa;b=this.C.V;c=this.C.Ia;d=this.C.xa;var e=this.C.ma,f=this.C.C;if(a&&(b.length||c.length||d.length||e.length||f.length)&&(DHf(this),this.F&&(this.F.initialize(a,b,this.C.Qa,c,this.C.Ea,d,this.C.Za,e,this.C.Ta,this.C.C,this.C.F),a=this.C.Ca,b=qHf(this.F.C.D),b.length==a.length)))for(c=0;c<b.length;c++)b[c].dc(a[c])}}};
m.FOa=function(){if(z(y(),"fecad")){var a=this.xa,b=this.R;a.C.C=[];a.C.F=[];a.C.J=[];var c=a.C;c.O=[];c.L=[];IGf(a,b)}};
m.OEb=function(a){if(a.C){var b=SM(this.D);if(!b)if(a.target instanceof rJ)b=a.target;else return;var c=b.F;a.C.some(function(e){return c.intersects(e)&&20<=e.height&&4<=e.width&&100<=e.height*e.width})?(this.Za=!0,this.V.start(500)):!this.Za&&this.V.Zb()&&(this.L=null!=this.J?1E3:5E3,this.V.start(this.L));QGf(this.xa,b,a.C);b={};a=ja(a.C);for(var d=a.next();!d.done;b={b9:b.b9},d=a.next()){b.b9=d.value;if(!this.H)break;if(!this.C.H)break;if(Vwa(this.C.H,b.b9)&&(!this.R||null!=this.J||!this.R.some(function(e){return function(f){return e.b9.equals(f.rect)}}(b)))){this.C.H=
null;this.R=[];null!=this.J?(this.L=1E3,this.V.start(this.L)):this.C.D=null;break}}}};m.S2b=function(){VM(this.D)&&!z(y(),"fedpsoi")&&(this.L=this.L||500,this.V.start(this.L))};m.P2b=function(){var a=SM(this.D);if(a){var b=yJ(a).x;RGf(this.xa,a,new zm(0,b,a.vg(),b+1,!1,!0));this.C.H=null;this.R=[];null!=this.J?(this.L=1E3,this.V.start(this.L)):this.C.D=null}};m.Rpb=function(){2<this.Pa?(this.Pa=0,this.J6(null)):(this.Pa++,this.Vfa())};
m.J6=function(a){this.Ca=!1;this.Pa=0;this.Za=!1;if((z(y(),"fenfts")||z(y(),"fetws")||z(y(),"ferds")||z(y(),"fecad"))&&!this.Qa){var b=this.ma.C,c=cK(this.O);if(this.H)if(a&&c&&b&&this.H&&b.C===this.H?(this.C.D=a,this.C.H=b.rect):(this.C.D=null,this.C.H=null),this.C.Oa=b,this.Ea||this.Oa)this.Lta();else{a=a?AHf(this,a.C):[];var d=this.C.C.length,e=a.length+d;if(!b||2>e)FHf(this);else if(!this.F||!this.F.isVisible()){for(var f=1<d,h=0,k=0,l=ja(a),n=l.next();!n.done;n=l.next())n=n.value,7==C(n,1)?(f=
f||C(C(n,14),3),h++):9==C(n,1)&&(f=!0,k++);f?0==k&&2>h?FHf(this):(null!=this.J?(c=this.J,c.J=b,NDf(c,a),c.H=d,b=LM(c.J.rect),b=z(y(),"feadpdp")?ky(KDf,{Qf:b,yha:c.D,Bha:c.F,zha:c.C,wha:c.H}):ky(LDf,{Qf:b,uXa:c.D+c.F+c.C+c.H}),a=c.Fa("waffle-assistant-popup-suggestion-text-container"),c.oa().vd(a),c.oa().appendChild(a,b)):this.Ta?(this.Lta(),this.Ia.C(36702,GHf(this,e))):EHf()||z(y(),"fedpsoi")||(this.Ia.C(36324,GHf(this,e)),this.J=QDf(c,this.O,this.$a,b,a,d)),this.C.R=null!=this.J):FHf(this)}}}};
function FHf(a){null!=a.J&&(a.Ia.C(36589),BHf(a))}function GHf(a,b){var c=new Qj;L(c,23,b);for(var d in XGf){b=new tT;switch(XGf[d]){case "number-format":L(b,1,1);L(b,2,a.C.V.length);break;case "trim-whitespace":L(b,1,2);L(b,2,a.C.xa.length);break;case "remove-duplicates":L(b,1,4);L(b,2,a.C.ma.length);break;case "anomaly":L(b,1,3);L(b,2,a.C.C.length);break;case "column-type":L(b,1,5);L(b,2,a.C.L.length);break;default:continue}qj(c,25,b,tT,void 0)}return Vy(Uy(Qy(new Py,76),c))}
function CHf(a){a.H&&IDf(a.D.F.L,a.D.D.D,a.H)}m.jAb=function(a){KGf(this.xa,this.R,a)};
m.Vfa=function(){if(this.H){if(!this.Ca&&!this.Ea&&!this.Oa){var a=this.D.F.L;if(!ej(a.C,2,!0))return;var b=this.D.D.D;a=ja(lj(a.C,IT,1));for(var c=a.next();!c.done;c=a.next())if(c=c.value,b===K(c,1)&&this.H===c.kb())return}this.L=null;b=SM(this.D);a=eK(this.O);b&&!this.D.Od()&&this.D.H.C&&!YM(this.D)&&a&&!a.F?(a=b.F,(c=this.C.H)&&Vwa(c,a)?((this.Ea||null!=this.J)&&this.J6(this.C.D),this.Ca=!1):IGe(this.ma)?(this.ma.reset(),jKe(this.ma),(b=yGf(b,a))?(b=TDf(b.getTableRange()),this.ma.O=b,tKe(this.ma,
!0,!0,!1,[7,8,9])):this.J6(null)):this.J6(null)):this.Ca=!1}};function EHf(){return"MERGED"===Mc(y(),"fdpfs")&&z(y(),"fects")&&z(y(),"fecis")&&z(y(),"fecad")}
function HHf(a,b,c,d,e,f,h,k,l,n,q){$V.call(this,b,h);var r=this;this.H=a;this.C=b;this.Ea=c;this.Pa=d;this.La=e;this.L=f;this.D=c.C;this.Ia=this.Ca=!1;this.F=null;this.V=k;this.Qa=q;this.J=null;IHf(this);eob.Na(!0);a=new Ej;L(a,6,JHf());b=new Bj;Fj(b,a);this.ma=Vy(Qy(Ry(new Py,b),10));this.xa=-1;a=new $p(function(){return KHf(r,!1)},100);this.va(a);a.start()}t(HHf,$V);
function IHf(a){var b=aH(a.La);a.Ma.listen(a.Pa,"selectionChange",a.bVb).listen(a.D,"ga",a.aVb).listen(a.D,"qa",a.dVb).listen(b,"nb",a.XOa).listen(a.C,"wd",a.Sob).listen(a.C,"vd",a.Rob).listen(a.C,"ud",a.Pob).listen(a.C,"Cd",a.$Eb).listen(a.C,"yd",a.nqb).listen(a.C,"Gd",a.kIb).listen(a.C,"Dd",a.FGb).listen(a.C,"xd",a.ppb).listen(a.C,"Hd",a.eVb).listen(a.H.C,"recommender-confidence-update",a.Qrb).listen(a.C,"Ed",a.cVb);Ts(Ts(Ts(Ts(Ts(Ts(Ss(a.O,fob,(Ms(),Ns),function(){a.C.Iga(!fob.isEnabled())}),hob,
function(){var c=a.C.isVisible();a.Sf().setVisible(!c);c||a.C.focus();LHf(a,!c)}),gob,function(c){ZFf(a.C,c.data)}),Gnb,function(){return MHf(a)}),Eqb,function(c){return NHf(a,c.data)}),zwb,function(){vGf(a.C,!0)}),VD,function(){return a.bL()})}m=HHf.prototype;m.Sf=function(){return iob};m.Cp=function(){return job};m.Ox=function(a){$V.prototype.Ox.call(this,a);gob.Na(a);KHf(this,!1);!this.Ca&&a&&(this.Ca=!0);var b={};SA(this.Qa,(b.je=a,b));a||this.C.Tc()};
m.j6=function(a){var b=this;this.C.Rza();var c=new $p(function(){$V.prototype.j6.call(b,a)},300);this.va(c);c.start()};m.bL=function(){$V.prototype.bL.call(this);LHf(this,!1)};m.QUa=function(a){this.C.RUa(a);this.H.C.La=a};m.Sob=function(a){var b=a.C.H,c=C(C(b,13),3);b=IV(b);var d=new Rg;dde(d,c);var e=new Iq;D(e,1,d);D(e,3,!0);tHe(e,!0);this.L.C(new KYe(e,b));y_(this,a.Xj(),!1,eYe(Pg(c)))};function LHf(a,b){b?(y_(a,2253),a.xa=La()):y_(a,2226,!0)}function MHf(a){a.C.isVisible()||a.Ox(!0)}
function NHf(a,b){var c="",d=void 0;b&&b.evt&&(c=b.evt?b.evt.C:"",d=b.evt);var e=tGf(a.C);e&&(e.Zb()?iFf(e,c,!0,!!c,d):(MHf(a),b=new $p(function(){hFf(e,c,!0,!!c,d)},1E3),a.va(b),b.start()))}m.dVb=function(){vV(this.H.C)||(this.H.C.reset(),KHf(this,!1))};m.bVb=function(){if(VM(this.Ea)&&null==this.C.O){var a=vV(this.H.C);a&&PI(this.D)!=a.kb()||KHf(this,!0)}};
function KHf(a,b,c){if(c){if(!c.length)return;if(1==c.length&&a.J&&c[0].equals(a.J)){a.J=null;return}}var d=a.C;d.isVisible()&&(d.La.refresh(void 0),aGf(d));a.H.update(!b,a.C.isVisible(),c)}
m.Qrb=function(a){var b=a.C,c=b?b.D:null;a=b?b.C:0;var d=!!b&&.9<=b.C,e=b?b.D.rect:null;e=!!e&&e.Ai()>=mlb&&Rm(e,"r")>=olb&&Rm(e,"c")>=plb&&e.Ai()<=nlb;b=!!b&&.6<=b.C&&e;if(b!==this.Ia||c&&!c.intersects(this.F))this.Ia=b,this.F=c,this.xa=La(),eob.Cb({Qea:b,oC:c});e&&c&&c.rect&&(b=1E3>=c.rect.Ai(),c=ritz_api.RitzModelApi.isFormsRegion(c.C,c.rect.top,c.rect.left,c.rect.height+c.rect.top,c.rect.width+c.rect.left),d=!this.C.isVisible()&&!this.Ca&&d&&b&&!yL(this.Ea.H),c=z(y(),"feeaof")&&c,b=z(y(),"feeaoro")&&
this.Ea.Od(),d&&(c||b)&&(d=new Ej,L(d,1,a),L(d,2,c),L(d,3,b),L(d,5,rlb),L(d,6,JHf()),a=new Bj,Fj(a,d),a=Vy(Ry(Qy(new Py,10),a)),this.mFa(a)))};m.mFa=function(a){var b=this;if(TI(this.D)&&!GJ(WI(this.D))&&(this.C.zc=!0,!AC.jca().C)){var c=a||this.ma;this.Sf().setVisible(!0);this.V.C(2225,c);y_(this,2253);a=new $p(function(){b.C.isVisible()||b.V.C(2752,c)},5E3);this.va(a);a.start()}};
function JHf(){switch(qlb){case "NO_DELAY":return 1;case "DELAY_500MS":return 2;case "DELAY_1S":return 3;case "DELAY_2S":return 4;default:return 0}}m.ppb=function(){this.C.Tc()};m.eVb=function(a){var b=a.C,c=IV(b.H);this.J=yn(c);Ife(this.L.D);tFf(b,c);y_(this,a.Xj())};m.aVb=function(){TI(this.D)?(this.C.Na(!0),this.H.C.reset(),KHf(this,!1)):(this.Sf().setVisible(!1),this.H.C.reset(),this.C.Na(!1))};m.XOa=function(a){KHf(this,!1,pRb(a))};
m.Rob=function(a){var b=WI(this.D),c=b.fc(),d=[],e=CYe(b);if(e){b=new br;var f=lg(e,2);D(b,3,f);f=lg(e,2);D(b,2,f);e=lg(e,1);D(b,1,e);d.push(b)}b=a.C.Xd;for(e=0;e<b.length;e++)f=new br,D(f,2,b[e]),d.push(f);this.L.C(new JYe(d,c));y_(this,a.Xj())};
m.Pob=function(a){var b=a.C,c=qYe(b.C),d=IV(b.H),e=c.oy?c.nB:null,f=c.C?c.OA:null,h=d.kb(),k=OHf(d);this.J=yn(d);k?(c=new MYe(k,h,this.J,e,c.Yw,c.gy,f),ZJ(c,function(l){l&&a.D.call()}),this.L.C(c)):(c=new HYe(h,this.J,e,c.Yw,c.gy,f),ZJ(c,function(l){l&&a.D.call()}),this.L.C(c));d=new pJd;L(d,1,1);c=new eT;fHe(c,C(b.H,2));mj(c,5,d);b=wRe(this.F,PI(this.D));yV(b,c);b=Vy(Ry(Qy(new Py,10),b));this.V.C(a.Xj(),b)};
m.$Eb=function(a){var b=a.C,c=IV(b.H),d=OHf(c);this.J=yn(c);d=new IYe(d);ZJ(d,function(e){e&&a.D.call();tFf(b,c)});this.L.C(d)};m.cVb=function(a){var b=zGe(a.getTableRange()),c=bEf(b,a.D,a.O),d=this.H,e=a.D;jKe(d.C);d.C.O=b;d.C.Ca=c;d.C.Ea=e;tKe(d.C,!0,!0,!1);y_(this,a.Xj());a.getTableRange().C!=PI(this.D)&&(c=a.getTableRange().C,c=XI(this.D,c))&&(c=aH(c),this.Ma.listen(c,"nb",this.XOa));a.F&&(tGf(this.C)&&tGf(this.C).bS(!0,!1,!0),a=this.C,b=[b],a.isVisible()&&(a.La.refresh(b),aGf(a)))};
function OHf(a){var b=a.kb();a=yn(a);b=ritz_api.RitzModelApi.getWorkbookRangeIntersectingIds(b,a.Ac(),a.tc(),a.Xc(),a.Wc(),7,!1);return 0<b.length?b[0]:null}m.nqb=function(a){var b=a.Qa;NI(WI(this.D),b);y_(this,a.Xj())};
m.kIb=function(a){var b=a.C;a=a.Xj();if(b instanceof aX||b instanceof bXe||b instanceof GFf)y_(this,a,void 0,void 0,b.sK());else{var c=$Ff(this.C),d=new eT,e=C(b.H,2);c=c.indexOf(b);L(d,1,c);fHe(d,e);e=new Bj;yV(e,d);if(b instanceof FEf){(d=b.D)?(b=PHf(this,b,d),b=wtd(b,d,d.Zk)):b=null;if(!b)return;mj(e,39,b)}else if(b instanceof ZEf){var f=b.H;c=new nJd;if(b instanceof ZEf)b=1;else throw Error("Unknown text analysis card type.");f=kg(JV(f),20).slice(0,10);L(c,2,f||[]);L(c,1,b);mj(d,3,c)}e=Vy(Ry(Qy(new Py,
10),e));this.V.C(a,e)}};m.FGb=function(){this.C.Tc()};function PHf(a,b,c){a=$Ff(a.C).filter(function(f){return f instanceof FEf});var d=a.map(function(f){return f.ze()}),e=a[0]&&C(a[0].J,29);return utd(c,a.indexOf(b),b.D&&b.D.Ue(),d,e)}
function y_(a,b,c,d,e){e=void 0===e?10:e;if(a.F){var f=N(Uj(a.ma),Ej,58).getTableRange();if(c||!f||f.kb()!=a.F.C||f.tc()!=a.F.rect.tc()||f.Ac()!=a.F.rect.Ac()||f.Wc()!=a.F.rect.Wc()||f.Xc()!=a.F.rect.Xc()){f=new Ej;L(f,6,JHf());var h=vRe(a.F);mj(f,7,h);c&&(c=La()-a.xa,L(f,8,1E3*c),null!=a.C.Ub&&(c=La()-a.C.Ub,L(f,10,1E3*c)));d&&hHe(f,d);d=new Bj;Fj(d,f);a.ma=Vy(Qy(Ry(new Py,d),e))}}a.V.C(b,a.ma)}function QHf(){OJ.apply(this,arguments)}t(QHf,OJ);m=QHf.prototype;m.tlb=function(){return KFf};m.bkb=function(){return rGf};
m.Tkb=function(){return yHf};m.Jkb=function(){return lEf};m.akb=function(){return HHf};m.Vjb=function(){return eEf};m.Lkb=function(){return nEf};TJ("assistant",QHf);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               