o contrato do usuário com o Google incluirá sempre, no mínimo, os termos e condições apresentados neste documento. Esses termos serão denominados a seguir como “Termos Universais”. As licenças de software do código-fonte do Google Chrome são concedidas por acordos firmados à parte. Até a extensão permitida pelas licenças de software de código aberto que substituem explicitamente estes Termos Universais, as licenças de código aberto regem seu contrato com o Google para uso do Google Chrome ou de componentes específicos incluídos no Google Chrome.</p>
<p>1.3. O contrato do usuário com o Google também incluirá os termos estabelecidos a seguir nos Termos de Serviço Adicionais do Google Chrome e nos termos de quaisquer Avisos legais aplicáveis aos Serviços, além dos Termos Universais. Todos esses termos serão denominados a seguir como “Termos Adicionais”. Nos casos em que os Termos Adicionais se aplicarem a um Serviço, esses termos ficarão disponíveis para leitura por parte do usuário nesse Serviço ou por meio do uso do mesmo.</p>
<p>1.4 Os Termos Universais, juntamente com os Termos Adicionais, formam um acordo com efeito jurídico entre o usuário e o Google com relação ao uso dos Serviços por parte do usuário. É importante que o usuário os leia com atenção. Coletivamente, este contrato é denominado “Termos”.</p>
<p>1.5 Caso haja alguma contradição entre o que indicam os Termos Adicionais e o que indicam os Termos Universais, os Termos Adicionais deverão prevalecer com relação a esse Serviço.</p>
<p><strong>2. Aceitação dos Termos</strong></p>
<p>2.1 Para usar os Serviços, o usuário deverá primeiro concordar com os Termos. Não é permitido o uso dos Serviços por parte do usuário se ele não aceitar os Termos.</p>
<p>2.2 O usuário pode aceitar os Termos:</p>
<p>(A) clicando para aceitar ou concordar, no caso de essa opção ser disponibilizada pelo Google na interface do usuário do Serviço; ou</p>
<p>(B) usando efetivamente os Serviços. Nesse caso, o usuário compreende e aceita que o Google considerará o seu uso dos Serviços uma aceitação dos Termos a partir desse momento.</p>
<p><strong>3. Idioma dos Termos</strong></p>
<p>3.1 No caso de o Google fornecer uma tradução da versão em língua inglesa dos Termos, o usuário concorda que essa tradução é fornecida apenas para sua conveniência e que a versão em língua inglesa dos Termos regerá o seu relacionamento com o Google.</p>
<p>3.2 Se houver alguma contradição entre o que indica a versão em inglês dos Termos e o que indica uma tradução, a versão em inglês deverá prevalecer.</p>
<p><strong>4. Prestação dos Serviços pelo Google</strong></p>
<p>4.1 O Google tem subsidiárias e entidades afiliadas em todo o mundo (“Subsidiárias e Afiliadas”). Ocasionalmente, essas empresas prestarão os Serviços ao usuário em nome do próprio Google. O usuário tem conhecimento e concorda que as Subsidiárias e Afiliadas têm direito de prestar os Serviços.</p>
<p>4.2 O Google está constantemente inovando para poder oferecer a melhor experiência possível aos seus usuários. O usuário tem conhecimento e aceita que a forma e a natureza dos Serviços fornecidos pelo Google podem mudar ocasionalmente sem aviso prévio ao usuário.</p>
<p>4.3 Como parte dessa constante inovação, o usuário tem conhecimen