p>
<p>"Nyckel" avser ett kryptografiskt värde i programvaran från Adobe som används för att dekryptera digitalt innehåll.</p>
<p>(b). Licensbegränsningar. Underlicenstagarens rätt att använda licenserna med avseende på programvaran från Adobe är underställd följande ytterligare begränsningar och åtaganden. Underlicenstagaren ska säkerställa att underlicenstagarens kunder följer dessa begränsningar och åtaganden i samma utsträckning som de gäller för underlicenstagaren med avseende på programvara från Adobe. Om underlicenstagarens kunder inte följer dessa ytterligare begränsningar och åtaganden ska detta anses vara ett betydande avtalsbrott från underlicenstagarens sida.</p>
<p>b.1. Underlicenstagaren och kunderna får endast distribuera programvara från Adobe som uppfyller reglerna för överensstämmelse och stabilitet som bekräftats av underlicenstagaren under verifieringsprocessen som beskrivs ovan i Adobes villkor.</p>   
<p>b.2. Underlicenstagaren får inte (i) kringgå funktionerna för innehållsskydd i varken programvaran från Adobe eller någon relaterad programvara från Adobe som används för att kryptera eller dekryptera digitalt innehåll för behörig användning av användare av programvaran från Adobe eller (ii) utveckla eller distribuera produkter som är avsedda att kringgå funktionerna för innehållsskydd i vare sig programvaran från Adobe eller någon annan programvara från Adobe som används för att kryptera eller dekryptera digitalt innehåll för behörig användning av användare av programvaran från Adobe.</p>
<p>(c) Nycklarna tillkännages härmed som Adobes konfidentiella information. Underlicenstagaren ska, med avseende på nycklarna, följa Adobes procedur för hantering av källkod (tillhandahålls av Adobe på begäran).</p>  
<p>(d) Domstolsföreläggande. Underlicenstagaren medger att ett brott mot detta avtal kan äventyra funktionerna för innehållsskydd i programvaran från Adobe och kan orsaka avsevärd och bestående skada för Adobe och ägare av digitalt innehåll, som är beroende av sådana funktioner för innehållsskydd, och att ekonomisk ersättning kanske inte helt kan kompensera för sådan skada. Därför accepterar underlicenstagaren att Adobe kan ha rätt att söka domstolsföreläggande för att förhindra eller begränsa den skada som orsakats av ett sådant avtalsbrott, utöver ekonomisk ersättning.</p>
<p>17. Avsedd tredjepartsförmånstagare. Adobe Systems Incorporated och Adobe Software Ireland Limited är avsedda tredjepartsförmånstagare i Googles avtal med underlicenstagare med avseende på programvara från Adobe, inklusive men utan begränsning till Adobes villkor. Underlicenstagaren accepterar, oaktat vad som står i dennes avtal med Google, att Google kan avslöja underlicenstagarens identitet för Adobe och skriftligen intyga att underlicenstagaren har ingått ett licensavtal med Google som inkluderar Adobes villkor. Underlicenstagaren måste ha ett avtal med var och en av sina licenstagare, och om licenstagarna tillåts vidaredistribuera programvaran från Adobe ska avtalet inkludera Adobes villkor.</p>
</body>
</html>
sv-SE,sv,en-US,enwindows-1252Från $1:På en inbäddad sida på $1 står detPå den här sidan står detPå en inbäddad sida på den här sidan står detHindra sidan från att skapa fler dialogrutorVill du lämna webbplatsen?Vill du lämna appen?Ändringar som du har gjort kanske inte sparas.Vill du läsa in webbplatsen igen?Vill du läsa in appen igen?Logga in och aktivera synkronisering så kan du använda korten på alla enheter.Aktivera synkronisering så kan du använda korten på alla enheter.$1 om du vill använda dina kort på alla enheter.FaktureringsadressVill du spara kortet?Vill du spara det här kortet i ditt Google-konto?Vill du spara kortet i Google-kontot?K