#!/usr/bin/env bash

[ $# -eq 0 ] && exit

if [ $1 = "install" ] 
then
    sudo ln -s "$PWD/mman" /usr/bin/mman
    exit
fi

if [ $1 = "fzf" -a $2 = "vim" ]
then 
    cd /home/aman/my/github/manual
    nvim $(fzf)
    exit
fi

if [ $1 = "fzf" ]
then 
    cd /home/aman/my/github/manual
    bat $(fzf)
    exit
fi



[ ! -f /dev/shm/mman ] && echo /home/aman/my/github/manual > /dev/shm/mman
    

cd $(cat /dev/shm/mman)
$@

echo $PWD > /dev/shm/mman

