#!/usr/bin/env bash

SCRIPT_PATH='/home/aman/data/git/my/my-notes-cum-tutorial/'

axit() {
    exit
}

show_help() {
    echo "fzf : show file to open in batcat"
    echo "fzf vim : select file to open in vim"
    axit
}

install() {
    sudo ln -s "$PWD/mman" /usr/bin/mman
    axit
}

fzf_vim() {
    cd ${SCRIPT_PATH}
    nvim $(fzf)
    axit
}

fzf_cat() {
    cd ${SCRIPT_PATH}
    batcat $(fzf)
    axit
}

parse_args() {
    [ $# -eq 0 ] && axit

    [ $1 = "install" ] && install

    [ $1 = "--help" ] && show_help


    [ $1 = "fzf" -a $2 = "vim" ] && fzf_vim

    [ $1 = "fzf" ] && fzf_cat
}

parse_args $@


[ ! -f /dev/shm/mman ] && echo ${SCRIPT_PATH} > /dev/shm/mman
    
cd $(cat /dev/shm/mman)
$@

echo $PWD > /dev/shm/mman
