t": 9,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[<matplotlib.lines.Line2D at 0xbcf1710>,\n",
       " <matplotlib.lines.Line2D at 0xbcf1940>]"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXoAAAEACAYAAAC9Gb03AAAABHNCSVQICAgIfAhkiAAAAAlwSFlz\nAAALEgAACxIB0t1+/AAAIABJREFUeJztnXl4VNX5xz8nAQJhkU1ZBFktVQQFgSAUiFSSFKxU3PuT\nVtSqdQEalyog4AJqsVGDa0VRW1eIawKZATGJIKCyCLIoIGBAkUXZCSSZ9/fHncQkTJJJZrnb+TzP\nfczcuXPOyzjzzrnv8j1KRNBoNBqNc4kx2wCNRqPRRBbt6DUajcbhaEev0Wg0Dkc7eo1Go3E42tFr\nNBqNw9GOXqPRaBxOyI5eKfWyUuonpdTaKq5JV0ptUkp9pZTqFeqcGo1GowmecKzoZwMplT2plBoO\ndBWRM4GbgOfCMKdGo9FogiRkRy8inwK/VHHJJcCr/muXA02VUq1CnVej0Wg0wRGNGP3pQH6ZxzuA\ndlGYV6PRaDRELxmrKjzWugsajUYTJepEYY6dQPsyj9v5z5VDKaWdv0aj0dQCEam4mC5HNFb0HwJ/\nAVBK9Qf2i8hPgS4UkagePp+P8ddfj8/nQ3btQpKS8A0cyPhevfBh3Hb4gPFt2uBr1gzf5Zczvnt3\n41xCgvE6/1hTpkwJet7MzFySkiYyZMgUkpImkpmZS58+U/wzlj+aNbsq4PkWLa4MeL5Jk0nUqzcx\n4HPJyZMC2lMT2614WNn++ffdR7b//8D8uDiyn3sOX1GR8fnxn58MjD///HKfJzsdVn7/3WB/MISj\nvPJN4DOgm1IqXyl1vVLqZqXUzQAiMg/4Tim1GXgBuDXUOcOFJyMD5szB+8AD0Ls39O2L5447SPnm\nm9JYkwKSDxzAm56Op1EjUtatM86tXYv33XdrPGdWVh7jxnnweh8mN3cqXu/DXH21h1Wrdge8vmPH\nRnTpMrHcuS5dJnD77UMCnn/jjWH07Bn4Rq2gILbG9mpqj3z/PZ4ZM0jyP04+fpzsV14h+913SVm7\ntvxnbNUqvP/736+vDfILrNEEQ8ihGxG5Johrbg91nnAjIngef5y0Q4dInT6dpMxMVFISOWPGENen\nD0uVKndtwcKFnNi4kTT/ueSjR0mdMYOkUaNQqsq7pnKkp3vZsmVauXOHD0+jZ88bOXJkYrnnunSZ\nwEMP/QWAmTPvp6Aglvr1i7njjhRGjBhM3755Ac+np3sDzl2/fjFZWXmkp3s5frwOcXFFjB2bFPBa\nTYgUFuIZNowUpco79LVref255+hc5jOWs3UrUljI8bvuInnUKCQ+ntQbbyRt1qwafbY0msqIRoze\nkngyMkhZvdr48tWti/fQIZKBR2fPDnh99ty5qDlzTvrSet99l+TLLiMxMTGoeY8fD/yWN2vWjunT\nhwZ03EDpf8syYsTggOfHjk1iy5byPxqxsRPYvbsdd9zhYevWX89v2TKRG244LSjbrUqw731Uue8+\nco4eJe6CC05aNJzeoQMPlPmc5eTkkDh4MNxwA4wcief66407zeHDSb7sMjOsrxGWfP9rgN3tDwZl\nlVtEpZREyxYRIbV/f9I+/xyFESdNTUggbenSSldQ944ZQ9x33xnPnzgBX3yB9OzJ8Z49K/1xC