lue="tabOrder" type="UINT" />
	</array>
	<array id="fontMap" itemname="fontLink">
		<field value="fontSize" type="double" />
		<field value="codePage" type="DWORD" />
		<field value="facename" type="BSTR" />
		<field value="lineSpace" type="int" />
		<field value="os" type="BSTR" />
	</array>
	<enum id="RichStaticLinkStatus">
		<metadata type="enum">
			<enum xtmlvalue="Normal" value="0" />
			<enum xtmlvalue="MouseOn" value="1" />
			<enum xtmlvalue="MouseDown" value="2" />
		</metadata>
	</enum>
	<enum id="EGFScrollBarType">
		<metadata type="enum">
			<enum xtmlvalue="Horz" value="0" />
			<enum xtmlvalue="Vert" value="1" />
		</metadata>
	</enum>
	<enum id="TabButtonHorizontalAlign">
		<metadata type="enum">
			<enum xtmlvalue="Left" value="0" />
			<enum xtmlvalue="Right" value="1" />
			<enum xtmlvalue="Center" value="2" />
		</metadata>
	</enum>
	<enum id="TabButtonState">
		<metadata type="enum">
			<enum xtmlvalue="UnpushedNormal" value="0" />
			<enum xtmlvalue="UnpushedHighlight" value="1" />
			<enum xtmlvalue="UnpushedPushed" value="2" />
			<enum xtmlvalue="PushedNormal" value="3" />
			<enum xtmlvalue="PushedHighlight" value="4" />
			<enum xtmlvalue="PushedPushed" value="5" />
		</metadata>
	</enum>
	<bitmask id="SysButtonStyle">
		<bit xtmlvalue="Minimize" value="0x0001" />
		<bit xtmlvalue="Maximize" value="0x0002" />
		<bit xtmlvalue="Close" value="0x0004" />
		<bit xtmlvalue="Restore" value="0x0007" />
	</bitmask>
	<bitmask id="liststyle">
		<bit xtmlvalue="LVS_ICON" value="0x0000"/>
		<bit xtmlvalue="LVS_REPORT" value="0x0001"/>
		<bit xtmlvalue="LVS_SMALLICON" value="0x0002"/>
		<bit xtmlvalue="LVS_LIST" value="0x0003"/>
		<bit xtmlvalue="LVS_SINGLESEL" value="0x0004"/>
		<bit xtmlvalue="LVS_SHOWSELALWAYS" value="0x0008"/>
		<bit xtmlvalue="LVS_SORTASCENDING" value="0x0010"/>
		<bit xtmlvalue="LVS_SORTDESCENDING" value="0x0020"/>
		<bit xtmlvalue="LVS_SHAREIMAGELISTS" value="0x0040"/>
		<bit 