  fourcc AVdv,AVd1   ; AVID DV
  fourcc dvhq,dvhp
  fourcc dvh5,dvh6,dvh3
  driver libdv
  dll libdv.so.2
  out YUY2

; note: it crashes with pond.dv :(
videocodec mcdv
  info "MainConcept DV Codec"
  status working
  fourcc DVSD,dvsd   ; PAL
  fourcc DVCS,dvcs   ; NTSC ?
  fourcc CDVC,cdvc   ; ???
  fourcc "dvcp" dvsd ; PAL DV in .mov
  fourcc "dvc " dvcs ; NTSC DV in .mov
  driver vfw
  dll "mcdvd_32.dll"
  out YUY2
  out UYVY
  out BGR32,BGR24,BGR15

; 3ivx:

videocodec 3ivXxa
  info "XAnim's 3ivx Delta 3.5 plugin"
  status working
  fourcc 3IV1
  driver xanim
  dll "vid_3ivX.xa"
  out YV12,IYUV,I420

videocodec 3ivX
  info "3ivx Delta 4.5"
  status working
  fourcc 3IV1
  driver dshow
  dll "3ivxDSDecoder.ax" ; 3ivx.dll is also required
  guid 0x0E6772C0, 0xDD80, 0x11D4, 0xB5, 0x8f, 0xA8, 0x6B, 0x66, 0xd0, 0x61, 0x1c
  out YV12
  out YUY2
  out BGR32,BGR24,BGR16,BGR15

; RealVideo variants

videocodec rv3040
  info "Linux RealPlayer 10 RV30/40"
  status buggy ; tries to use multi-threaded decoding on SMP systems and crashes on exit
  fourcc RV30,rv30
  fourcc RV40,rv40
  driver realvid
  dll "drvc.so"
  out I420

videocodec rv3040win
  info "Win32 RealPlayer 10 RV30/40"
  status working
  fourcc RV30,rv30
  fourcc RV40,rv40
  driver realvid
  dll "drvc.dll"
  out I420

videocodec rv40
  info "Linux RealPlayer 9 RV40"
  status buggy
  fourcc RV40,rv40
  driver realvid
  dll "drv4.so.6.0"
  out I420

videocodec rv40win
  info "Win32 RealPlayer 9 RV40"
  status working
  fourcc RV40,rv40
  driver realvid
  dll "drv43260.dll"
  out I420

videocodec rv40mac
  info "Mac OS X RealPlayer 9 RV40"
  status working
  fourcc RV40,rv40
  driver realvid
  dll "drvc.bundle/Contents/MacOS/drvc"
  out I420

videocodec rv30
  info "Linux RealPlayer 8 RV30"
  status buggy
  fourcc RV30,rv30
  driver realvid
  dll "drv3.so.6.0"
  out I420

videocodec rv30win
  info "Win32 RealPlayer 8 RV30"
  status working
  fourcc RV30,rv30
  driver realvid
  dll "drv33260.dll"
  out I420

videocodec r