flags})" },
		{ "trigger": "socket_sendto", "contents": "socket_sendto(${1:socket}, ${2:buf}, ${3:len}, ${4:flags}, ${5:addr})" },
		{ "trigger": "socket_set_block", "contents": "socket_set_block(${1:socket})" },
		{ "trigger": "socket_set_blocking", "contents": "socket_set_blocking()" },
		{ "trigger": "socket_set_nonblock", "contents": "socket_set_nonblock(${1:socket})" },
		{ "trigger": "socket_set_option", "contents": "socket_set_option(${1:socket}, ${2:level}, ${3:optname}, ${4:optval})" },
		{ "trigger": "socket_set_timeout", "contents": "socket_set_timeout()" },
		{ "trigger": "socket_shutdown", "contents": "socket_shutdown(${1:socket})" },
		{ "trigger": "socket_strerror", "contents": "socket_strerror(${1:errno})" },
		{ "trigger": "socket_write", "contents": "socket_write(${1:socket}, ${2:buffer})" },
		{ "trigger": "solr_get_version", "contents": "solr_get_version(${1:oid})" },
		{ "trigger": "sort", "contents": "sort(${1:array})" },
		{ "trigger": "soundex", "contents": "soundex(${1:str})" },
		{ "trigger": "spl_autoload", "contents": "spl_autoload(${1:class_name})" },
		{ "trigger": "spl_autoload_call", "contents": "spl_autoload_call(${1:class_name})" },
		{ "trigger": "spl_autoload_extensions", "contents": "spl_autoload_extensions()" },
		{ "trigger": "spl_autoload_functions", "contents": "spl_autoload_functions(${1:oid})" },
		{ "trigger": "spl_autoload_register", "contents": "spl_autoload_register()" },
		{ "trigger": "spl_autoload_unregister", "contents": "spl_autoload_unregister(${1:autoload_function})" },
		{ "trigger": "spl_classes", "contents": "spl_classes(${1:oid})" },
		{ "trigger": "spl_object_hash", "contents": "spl_object_hash(${1:obj})" },
		{ "trigger": "split", "contents": "split(${1:pattern}, ${2:string})" },
		{ "trigger": "spliti", "contents": "spliti(${1:pattern}, ${2:string})" },
		{ "trigger": "sprintf", "contents": "sprintf(${1:format})" },
		{ "