PDF_concat", "contents": "PDF_concat(${1:p}, ${2:a}, ${3:b}, ${4:c}, ${5:d}, ${6:e}, ${7:f})" },
		{ "trigger": "PDF_continue_text", "contents": "PDF_continue_text(${1:p}, ${2:text})" },
		{ "trigger": "PDF_create_3dview", "contents": "PDF_create_3dview(${1:pdfdoc}, ${2:username}, ${3:optlist})" },
		{ "trigger": "PDF_create_action", "contents": "PDF_create_action(${1:pdfdoc}, ${2:type}, ${3:optlist})" },
		{ "trigger": "PDF_create_annotation", "contents": "PDF_create_annotation(${1:pdfdoc}, ${2:llx}, ${3:lly}, ${4:urx}, ${5:ury}, ${6:type}, ${7:optlist})" },
		{ "trigger": "PDF_create_bookmark", "contents": "PDF_create_bookmark(${1:pdfdoc}, ${2:text}, ${3:optlist})" },
		{ "trigger": "PDF_create_field", "contents": "PDF_create_field(${1:pdfdoc}, ${2:llx}, ${3:lly}, ${4:urx}, ${5:ury}, ${6:name}, ${7:type}, ${8:optlist})" },
		{ "trigger": "PDF_create_fieldgroup", "contents": "PDF_create_fieldgroup(${1:pdfdoc}, ${2:name}, ${3:optlist})" },
		{ "trigger": "PDF_create_gstate", "contents": "PDF_create_gstate(${1:pdfdoc}, ${2:optlist})" },
		{ "trigger": "PDF_create_pvf", "contents": "PDF_create_pvf(${1:pdfdoc}, ${2:filename}, ${3:data}, ${4:optlist})" },
		{ "trigger": "PDF_create_textflow", "contents": "PDF_create_textflow(${1:pdfdoc}, ${2:text}, ${3:optlist})" },
		{ "trigger": "PDF_curveto", "contents": "PDF_curveto(${1:p}, ${2:x1}, ${3:y1}, ${4:x2}, ${5:y2}, ${6:x3}, ${7:y3})" },
		{ "trigger": "PDF_define_layer", "contents": "PDF_define_layer(${1:pdfdoc}, ${2:name}, ${3:optlist})" },
		{ "trigger": "PDF_delete", "contents": "PDF_delete(${1:pdfdoc})" },
		{ "trigger": "PDF_delete_pvf", "contents": "PDF_delete_pvf(${1:pdfdoc}, ${2:filename})" },
		{ "trigger": "PDF_delete_table", "contents": "PDF_delete_table(${1:pdfdoc}, ${2:table}, ${3:optlist})" },
		{ "trigger": "PDF_delete_textflow", "contents": "PDF_delete_textflow(${1:pdfdoc}, ${2:textflow})" },
		{ "trigger": "PDF_encoding_set_char", "contents": "PDF_encoding_set_char(${1:pdfdoc}, ${2:encoding}, ${3:slot}, ${4:glyphname}, ${5:uv})" },
		{ "trigger": "PDF_end_document", "contents": "PDF_end_document(${1:pdfdoc}, ${2:optlist})" },
		{ "trigger": "PDF_end_font", "contents": "PDF_end_font(${1:pdf