  "134",  "36",   "ETSI", "5G",   "40M",  "HT",   "1T",
	"134",  "30",   "MKK",  "5G",   "40M",  "HT",   "1T",   "134",  "30",
	"FCC",  "5G",   "40M",  "HT",   "1T",   "142",  "30",   "ETSI", "5G",
	"40M",  "HT",   "1T",   "142",  "63",   "MKK",  "5G",   "40M",  "HT",
	"1T",   "142",  "63",   "FCC",  "5G",   "40M",  "HT",   "1T",   "151",
	"36",   "ETSI", "5G",   "40M",  "HT",   "1T",   "151",  "63",   "MKK",
	"5G",   "40M",  "HT",   "1T",   "151",  "63",   "FCC",  "5G",   "40M",
	"HT",   "1T",   "159",  "36",   "ETSI", "5G",   "40M",  "HT",   "1T",
	"159",  "63",   "MKK",  "5G",   "40M",  "HT",   "1T",   "159",  "63",
	"FCC",  "5G",   "40M",  "HT",   "2T",   "38",   "26",   "ETSI", "5G",
	"40M",  "HT",   "2T",   "38",   "20",   "MKK",  "5G",   "40M",  "HT",
	"2T",   "38",   "22",   "FCC",  "5G",   "40M",  "HT",   "2T",   "46",
	"36",   "ETSI", "5G",   "40M",  "HT",   "2T",   "46",   "20",   "MKK",
	"5G",   "40M",  "HT",   "2T",   "46",   "22",   "FCC",  "5G",   "40M",
	"HT",   "2T",   "54",   "36",   "ETSI", "5G",   "40M",  "HT",   "2T",
	"54",   "20",   "MKK",  "5G",   "40M",  "HT",   "2T",   "54",   "22",
	"FCC",  "5G",   "40M",  "HT",   "2T",   "62",   "28",   "ETSI", "5G",
	"40M",  "HT",   "2T",   "62",   "20",   "MKK",  "5G",   "40M",  "HT",
	"2T",   "62",   "22",   "FCC",  "5G",   "40M",  "HT",   "2T",   "102",
	"28",   "ETSI", "5G",   "40M",  "HT",   "2T",   "102",  "20",   "MKK",
	"5G",   "40M",  "HT",   "2T",   "102",  "30",   "FCC",  "5G",   "40M",
	"HT",   "2T",   "110",  "36",   "ETSI", "5G",   "40M",  "HT",   "2T",
	"110",  "20",   "MKK",  "5G",   "40M",  "HT",   "2T",   "110",  "30",
	"FCC",  "5G",   "40M",  "HT",   "2T",   "118",  "36",   "ETSI", "5G",
	"40M",  "HT",   "2T",   "118",  "20",   "MKK",  "5G",   "40M",  "HT",
	"2T",   "118",  "30",   "FCC",  "5G",   "40M",  "HT",   "2T",