32",   "ETSI", "5G",   "20M",  "HT",   "1T",   "165",  "63",   "MKK",
	"5G",   "20M",  "HT",   "1T",   "165",  "63",   "FCC",  "5G",   "20M",
	"HT",   "2T",   "36",   "28",   "ETSI", "5G",   "20M",  "HT",   "2T",
	"36",   "20",   "MKK",  "5G",   "20M",  "HT",   "2T",   "36",   "22",
	"FCC",  "5G",   "20M",  "HT",   "2T",   "40",   "30",   "ETSI", "5G",
	"20M",  "HT",   "2T",   "40",   "20",   "MKK",  "5G",   "20M",  "HT",
	"2T",   "40",   "22",   "FCC",  "5G",   "20M",  "HT",   "2T",   "44",
	"30",   "ETSI", "5G",   "20M",  "HT",   "2T",   "44",   "20",   "MKK",
	"5G",   "20M",  "HT",   "2T",   "44",   "22",   "FCC",  "5G",   "20M",
	"HT",   "2T",   "48",   "30",   "ETSI", "5G",   "20M",  "HT",   "2T",
	"48",   "20",   "MKK",  "5G",   "20M",  "HT",   "2T",   "48",   "22",
	"FCC",  "5G",   "20M",  "HT",   "2T",   "52",   "30",   "ETSI", "5G",
	"20M",  "HT",   "2T",   "52",   "20",   "MKK",  "5G",   "20M",  "HT",
	"2T",   "52",   "22",   "FCC",  "5G",   "20M",  "HT",   "2T",   "56",
	"30",   "ETSI", "5G",   "20M",  "HT",   "2T",   "56",   "20",   "MKK",
	"5G",   "20M",  "HT",   "2T",   "56",   "22",   "FCC",  "5G",   "20M",
	"HT",   "2T",   "60",   "30",   "ETSI", "5G",   "20M",  "HT",   "2T",
	"60",   "20",   "MKK",  "5G",   "20M",  "HT",   "2T",   "60",   "22",
	"FCC",  "5G",   "20M",  "HT",   "2T",   "64",   "28",   "ETSI", "5G",
	"20M",  "HT",   "2T",   "64",   "20",   "MKK",  "5G",   "20M",  "HT",
	"2T",   "64",   "22",   "FCC",  "5G",   "20M",  "HT",   "2T",   "100",
	"26",   "ETSI", "5G",   "20M",  "HT",   "2T",   "100",  "20",   "MKK",
	"5G",   "20M",  "HT",   "2T",   "100",  "30",   "FCC",  "5G",   "20M",
	"HT",   "2T",   "104",  "30",   "ETSI", "5G",   "20M",  "HT",   "2T",
	"104",  "20",   "MKK",  "5G",   "20M",  "HT",   "2T",   "104",  "30",
	"FCC",  "5G",   "20M",  "HT",   "2T",   "108",  "32",   "ETSI", "5G",
	"20M",  "HT",   "2T",   "108",  "20",   "MKK",  "5G",   "20M",  "HT",
	"2T",   "108",  "30",   "FCC",  "5G",   "20M",  "HT",   "2T",   "112",
	"32",   "ETSI", "5G",   "20M",  "HT",   "2T",   "112",  "20",   "MKK",
	"5G",   "20M",  "HT",   "2T",   "112",  "30",   "FCC",  "5G",   "20M",
	"HT",   "2T",   "116",  "32",   "ETSI", "5G",   "20M",  "HT",   "2T",
	"116",  "20",   "MKK",  "5G",   "20M",  "HT",   "2T",   "116",  "30",
	"FCC",  "5G",   "20M",  "HT",   "2T",   "120",  "32",   "ETSI", "5G",
	"20M",  "HT",   "2T",   "120",  "20",   "MKK",  "5G",   "20M",  "HT",
	"2T",   "120",  "30",   "FCC",  "5G",   "20M",  "HT",   "2T",   "124",
	"32",   "ETSI", "5G",   "20M",  "HT",   "2T",   "124",  "20",   "MKK",
	"5G",   "20M",  "HT",   "2T",   "124",  "30",   "FCC",  "5G",   "20M",
	"HT",   "2T",   "128",  "32",   "ETSI", "5G",   "20M",  "HT",   "2T",
	"128",  "20",   "MKK",  "5G",   "20M",  "HT",   "2T",   "128",  "30",
	"FCC",  "5G",   "20M",  "HT",   "2T",   "132",  "32",   "ETSI", "5G",
	"20M",  "HT",   "2T",   "132",  "20",   "MKK",  "5G",   "20M",  "HT",
	"2T",   "132",  "30",   "FCC",  "5G",   "20M",  "HT",   "2T",   "136",
	"30",   "ETSI", "5G",   "20M",  "HT",   "2T",