ed=this.Ca;b.teamDriveAclFixerDialogEnabled=!0;b.shareClientJserrorReportingEnabled=
!0;return b};
var MX=function(b,c,d,e,f,g,k,l,n,q,u,w,E,G){vy.call(this);this.Na=b;this.ha=l||new Vzh(e);this.Va=n||window;b=TE.Rb();e=new bF(e,b);b=e.Fa();b||(e.Pa(),b=e.Fa());JA(b,"J-M-awN");e.setVisible(!1);this.Ca=e;b=ZE.Rb();(this.Db=new $E(Pd,void 0,void 0,b)).setEnabled(!1);(this.Ha=new $E("Sharing is unavailable at this time. Please try again later.",void 0,void 0,b)).setEnabled(!1);this.Wb=c;this.Sc=d;this.Gc=k||c;this.wa=new dAh({});this.Mb=e.Qa();this.Oa=f||null;this.qc=void 0!==g?g:!0;this.Gb=new Hzh;
this.Ka=u||null;this.Ea=!!q;this.hb=q||null;this.Ed=w||null;this.Tb=G||new Ezh;this.hc=null;this.hc=this.Mb.Fa("docs-aria-speakable");this.nb=null;eAh(this,E);this.Ea||fAh(this,this.Va);c=gAh(this);c.listen(e,hn,this.lac);c.listen(e,Cf,this.od);c.listen(this.ha,Azh,this.Zc);c.listen(this.ha,Bzh,this.vd);c.listen(this.ha,"errorHidden",this.yd);c.listen(this.ha,"errorShown",this.Cb)};F(MX,vy);v=MX.prototype;v.LMa=null;v.Vja=null;v.rM=null;v.ZEa=null;v.Jya="share";v.sT=!1;v.OS=!1;v.vZ=null;v.kea=null;
v.W8=null;v.Wa=null;v.Qt=null;v.sK=null;v.jab=null;v.uDa=!1;v.rDa=null;v.ceb=!1;v.c3=!1;v.fT=!1;v.QAb=!1;v.UM=null;v.$Ha=0;v.gQa=null;v.MEa=0;v.dha=null;v.Dbb=!1;v.zoa=!1;v.Yyb=!1;v.sD=null;
var fAh=function(b,c){b.Ea||(c.SC_setTitle=C(b.ukb,b),c.SC_resize=C(b.ha.resize,b.ha),c.SC_maximize=C(b.ha.maximize,b.ha),c.SC_setVisible=C(b.Dc,b),c.SC_prepareForVisible=C(b.Fb,b),c.SC_setClientModel=C(b.kSb,b),c.SC_dispatchEvent=C(b.Da,b),c.SC_handleError=C(b.kac,b),c.SC_handleCommandComplete=C(b.Xvb,b),c.SC_setExecuteCommandFn=C(b.Cfd,b),c.SC_switchShareApp=C(b.xjd,b),c.SC_setSetShareSystemVisibleFn=C(b.tgd,b),c.SC_setGetInterfaceVersionNumberFn=C(b.Ffd,b),c.SC_getVersionNumber=C(b.Kqc,b),c.SC_rewriteUrl=
C(b.ydd,b),c.SC_showNotification=C(b.mac,b),c.SC_removeNotification=C(b.ycd,b),c.SC_getAriaLiveRegion=C(b.Uc,b))},hAh=function(b){if(b.Ea&&!b.sD){var c=Vx(Tx(b.rM.clone(),"").Ig(""),"").toString();b.sD=new Xzh(null,c);b.wb(b.sD);Yzh(b.sD,"setClientModel",function(d){this.kSb(d.clientModelJson)},b);Yzh(b.sD,"handleCommandComplete",function(d){this.Xvb(d.commandType,d.commandStatus)},b);Yzh(b.sD,Bm,function(d){this.ha.resize(d.width,d.height);this.sD.sendMessage("resizeComplete")},b);Yzh(b.sD,"maximize",
function(){this.ha.maximize();this.sD.sendMessage("maximizeComplete")},b);Yzh(b.sD,"prepareForVisible",function(){this.Fb();this.sD.sendMessage("makeBodyVisible");this.sD.sendMessage("prepareComplete")},b);Yzh(b.sD,"setVisible",function(d){this.Dc(d.visible,d.fullScreen)},b);Yzh(b.sD,"setTitle",function(d){this.ukb(d.title,d.hidden)},b);b.kea=null;b.vZ=C(function(d){this.sD.sendMessage("executeCommand",{commandType:d})},b)}},iAh=function(b){var c={};c.impressionType=b;return c},jAh=function(b){var c=
"/sharing/share";if(b.rM)throw Error("Aca");typeof c===zn&&(c=new Qp(c));b.rM=c;b.Ea&&hAh(b)},lAh=function(b,c){c=rq(c)?c:[c];$q(c);br(c);var d=b.Qt;b.sT&&cr(c,d)||(b.Qt=c,b.sT=!1,b.zoa=!1,b.MEa=0,b.ZEa=null,b.Aa(xxa),b.ha.isVisible()&&kAh(b,!1))};v=MX.prototype;v.Kqc=t(2);
v.kSb=function(b){var c=this.wa;b=nr(b);var d=b.userScope;d&&(b.userScope=cAh(d));(d=b.visibilitySetting)&&(b.visibilitySetting=new Wzh(d.visibilityState,d.summary,d.details,d.role,d.restrictedToDomain,d.key,d.domainDisplayName,d.restrictedToSingleUserScope,d.hasInvalidEntries,d.publishVisibilityState||ro,d.hasNamedPartiesForPublish||!1));this.wa=new dAh(b);this.sT&&c.ha!=this.wa.ha&&(this.Dbb=!0);this.sT=!0;this.c3=!1;c=this.wa.Va;c!=qzh&&(c="share");c!=this.Jya&&(b=this.rM.clone(),b=mAh(b,c),this.OS=
!1,this.rM=b,this.Jya=c);nAh(this);c=this.wa;this.$Ha=Kzh(this.Mb).length;this.Gb.WX(this.Ca,c.Aa,c.wa,oAh(this),c.Ea&&!1,this.Qt?this.Qt.length:0,this.Mb,c.Ga,c.Ca,c.Da);this.Da(xzh);this.Ib();this.dha&&(this.dha.ha(this.wa.Ba),this.dha.wa(this.wa.Ia,this.wa.Na));this.Da(ozh)};v.lac=function(){if(this.Qt&&this.Qt.length)this.sT?pAh(this):(this.Ca.isVisible()||this.Ca.setVisible(!0,!0),this.Ia(!0));else{nAh(this);for(var b=Kzh(this.Mb),c=b.length-1;0<=c;c--)qAh(this,b[c])}};
v.kac=function(b,c){switch(b){case wj:nAh(this),c?(b=ZE.Rb(),c=new $E(GIa(document,Er(Hh,void 0,c)),void 0,void 0,b),c.setEnabled(!1),qAh(this,c)):qAh(this,this.Ha),this.sT=this.zoa=!0}};
v.Xvb=function(b,c,d){c=c==Cn;switch(b){case wj:rAh(this);break;case tzh:case rh:c&&(this.MEa=uq());a:{this.fT=!1;b=this.UM;d=this.Ba||{};if(this.uDa)if(this.uDa=!1,this.Qt=this.jab,delete this.jab,this.UM=null,delete this.Ba,delete this.Ga,c){if(b){d.itemIds=this.Qt;this.sK&&(d.hybrid_access_token=this.sK);sAh(this,b,d);break a}}else b==wzh&&tAh(this);b&&(c?(c=C(this.kb,this,b,this.Ba,this.Ga),Sy(c,10,this)):b==wzh&&tAh(this),this.UM=null,delete this.Ba,delete this.Ga)}break;case en:case Jna:case "link_settings":case "email_attach":c||
this.ha.WE(!0,d||"")}};v.Ffd=p();v.Cfd=function(b){this.OS=!0;this.kea=this.vZ;this.vZ=b};v.xjd=function(b,c){KHa&&(this.W8=null);c&&c.forceFullLoad&&(this.OS=!1);var d=this.vZ;this.kea?this.vZ=this.kea:this.OS=!1;this.kea=d;uAh(this);c=c||{};c.share_app_switched=!0;this.Aa(b,c)};v.tgd=np("W8");v.ydd=mp();v.mac=function(b){var c=this.ha;Uzh(c.Aa,new Gzh(b.iconId,b.message,b.showInDialog,b.timeout,b.learnMoreUrl,b.undoFn),c.ha.Fa())};v.ycd=function(){this.ha.Aa.Aa()};
v.ukb=function(b,c){this.ha.setTitle(b,c)};var oAh=function(b){var c=b.wa.Aa;return b.wa.wa?!1:40==c||45==c||35==c||30==c&&b.wa.Ka};MX.prototype.Uc=r(Pi);var eAh=function(b,c){c&&(b.nb=function(){var d=c(),e=new Ap(function(f){Ip.setTimeout(f,1500)});return Ap.race([d,e])})};
MX.prototype.Ia=function(b,c,d){this.Qt&&!Pq(this.Qt)&&(this.ha.isVisible()?this.LMa=C(this.Ia,this,b,c):(b&&(nAh(this),qAh(this,this.Db),Sy(this.Ob,9E3,this)),this.c3||(this.OS?(this.c3=!0,vAh(this,d,!0)):(this.ceb=this.c3=!0,c=this.rDa,c||(c=Fs(nd),ds&&!ls("7")&&Or(c,wr(xp(Xua))),d=c.style,d.visibility=Ui,d.width=d.height=pda,QA&&!ls("419.3")?d.marginTop=d.marginLeft="-99px":(d.position=yf,d.top=d.left="-10px"),document.body.appendChild(c),this.rDa=c),c.src=wAh(this,wj),Sy(this.Fc,2E4,this),b&&
pAh(this)))))};
var pAh=function(b){if(!b.zoa)if(b.fT||b.OS){var c;if(c=b.OS)c=2E4<uq()-b.MEa;c&&(b.fT=!0,vAh(b,void 0,!0))}else b.fT=!0,xAh(b,ro,!0)},xAh=function(b,c,d){var e={};e.locationHint=c;e.preload=!!d;c=b.rM?xB(wAh(b,tzh,e)):j0b;c='<iframe frameborder="0" src="'+O(p7a(c))+va+O("Qr-Mr-Jz-avO")+La+O("Sharing")+kca;c=L(c).wj();b.ha.setContent(c);d||yAh(b,!0);b.Fb()},vAh=function(b,c,d){c=c||{};c.itemIds||(c.itemIds=b.Qt);c.locationHint||(c.locationHint=b.ZEa);!c.hybrid_access_token&&b.sK&&(c.hybrid_access_token=b.sK);
b.kb(rh,c,void 0,d)},nAh=function(b){for(var c=b.Ca,d=b.$Ha,e=0;e<d;e++)c.Ls(0,!0);b.$Ha=0;b.Da(xzh)},qAh=function(b,c){c.getParent()||(b.Ca.Gh(c,0,!0),b.$Ha++,b.Da(xzh))},gAh=function(b){return b.Wa||(b.Wa=new Qz(b))};MX.prototype.CKa=function(){this.ha.CKa()};
var wAh=function(b,c,d){if(!b.rM)return k0b;var e=b.rM.clone();if(c==wj)e=mAh(e,wj);else if(c==tzh&&b.UM&&(b.UM==wzh||b.UM==vzh))e=mAh(e,qzh);else if(d){var f=d.locationHint;f||lr(d,"locationHint");"teamDriveRoot"==f||"teamDriveItem"==f?e=mAh(e,qzh):"myDriveItem"==f&&(e=mAh(e,"share"))}Up(e,nj,b.Qt);Up(e,pta,b.Wb);Up(e,"gaiaService",b.Sc);Up(e,"shareService",b.Gc);c!=wj&&Up(e,eh,c);Up(e,"subapp",10);Up(e,yzh,b.qc);Up(e,"shareUiType",vh);b.Oa&&Up(e,Yi,b.Oa);b.sK?Up(e,szh,b.sK):Up(e,fg,b.Na?b.Na:"0");
Up(e,"rand",uq());d&&e.wa.Ca(d);b.Ea&&Up(e,ora,"postMessage");b.Ka&&Up(e,"appId",b.Ka);b.hb&&Up(e,"embedOrigin",b.hb);return e.toString()},mAh=function(b,c){return Tx(b,b.getPath().replace(/[a-z]+$/,c==qzh||c==wj?c:"share"))};
MX.prototype.Aa=function(b,c){c=c||{};c.itemIds=this.Qt;c.triggerInstantMs=uq();this.sK&&(c.hybrid_access_token=this.sK);!c.locationHint&&this.ZEa&&(c.locationHint=this.ZEa);fAh(this,this.Va);var d=!0;switch(b){case wj:case vzh:case "maybe_email_collaborators":case wzh:case zzh:case xxa:case Am:d=!1}switch(b){case wzh:zAh(this,!0)}if(b==Am)this.Ob();else if(!this.OS&&this.Qt&&15<this.Qt.length)this.jab=this.Qt,this.Qt=[this.Qt[0]],this.uDa=!0,sAh(this,b,c,!d);else if(b==wj||b==xxa)this.Ia(!1,!0,c);
else if(!this.Qt||!this.Qt.length)this.dispatchEvent(new AAh(C(this.Aa,this,b,c)));else if(c.share_app_switched||this.dispatchEvent(new BAh(b,c))){if("invite"==b&&c.inviteFromUrl){if(this.sT&&!oAh(this))return;if(!this.sT){this.c3||this.Ia(!1,!0);gAh(this).Bd(this,ozh,C(this.Aa,this,b,c));return}}b==en&&!c.itemContentSummaryPromise&&this.nb&&(c.itemContentSummaryPromise=this.nb());var e;if(!(e=!this.OS)&&(e=2E4<uq()-this.MEa)){a:switch(b){case vzh:case wzh:e=!0;break a;case zzh:e=!0;break a;default:e=
!1}e=!e}e?((this.uDa&&d||c.itemContentSummaryPromise)&&yAh(this,!0),sAh(this,b,c,!d)):this.kb(b,c)}};var sAh=function(b,c,d,e){b.UM=c;b.Ba=d;b.Ga=(new Date).getTime();typeof b.Vja===ll&&Ty(b.Vja);b.Vja=Sy(b.Kc,2E4,b);b.fT||(b.fT=!0,b.OS?b.c3||vAh(b,d,c==vzh||c==wzh):(c=ro,d&&d.locationHint&&(c=d.locationHint),xAh(b,c,e)))};
MX.prototype.kb=function(b,c,d,e){if(b!=zzh){var f=c||{};f.itemIds||(f.itemIds=this.Qt);!f.hybrid_access_token&&this.sK&&(f.hybrid_access_token=this.sK);if(b==wzh||b==vzh)f.aclFixerMode=f.aclFixerMode||uva;fAh(this,this.Va);(c=f.itemContentSummaryPromise)?c.then(function(g){yAh(this,!1);g?f.itemContentSummaryInfo=g:f.itemContentSummaryPromiseTimeout=!0;this.vZ(b,f,d,e)},void 0,this):this.vZ(b,f,d,e)}};var rAh=function(b){var c=b.rDa;c&&(Ns(c),b.rDa=null)};
MX.prototype.Fc=function(){this.ceb&&(rAh(this),this.ceb=!1)};MX.prototype.Ob=function(){this.c3&&!this.zoa&&(nAh(this),qAh(this,this.Ha),this.c3=!1,this.zoa=!0)};
MX.prototype.Kc=function(){if(this.fT){var b=!1;switch(this.UM){case wzh:tAh(this);break;case vzh:case zzh:break;default:b=!0,this.ha.WE(!0,"Sorry, sharing is unavailable at this time. Please try again later.")}this.Da(uzh);if(this.rM){v