totype.Se=np("Dc");bY.prototype.Kt=function(){return this.Dc||this.getParent()&&this.getParent().Kt&&this.getParent().Kt()};
var CPh=function(b){var c=new fPh(b.Mb);c.Tj(!1);c.qD=!1;cF(c,!1);c.gR=!0;c.Pa();c.Fa().tabIndex=-1;JA(c.Fa(),"fx");c.Yg(b);return c},KPh=function(b,c,d,e){if(d){var f=cY(b,c);f&&(f.$j(d),d.Ca=f,b.Ll.ha.appendChild(d.Fa()),b.Wa.listen(d,Kna,C(f.Ni,f,!1)),b=cY(b,c),e=new hrb(b.Fa(),e||8,!1,!0),b.HE(e))}},FPh=function(b,c,d){BPh(b,d)&&(b=b.Fa(d))&&c.getHandler().Xc(b,Ok,c.lvb)};bY.prototype.od=function(){this.Gb=!1};
var LPh=function(b){if(kr(b.Ib))for(var c in l8g){var d=l8g[c],e=null,f=null,g=!0,k=!0,l=!1;switch(c){case H7g:k=!1;e="Z";break;case E7g:k=!1;e="Y";break;case UW:k=!1;e="B";break;case ZW:k=!1;e="I";break;case cX:k=!1;e="U";break;case A7g:e="7";break;case B7g:e="8";break;case TW:e="9";break;case bX:k=!1;e="[";break;case z7g:k=!1;e="]";break;case $W:e="L";break;case D7g:e="R";break;case C7g:e="E";break;case WW:e="5";f="6";break;case XW:e="-";f="+";break;case sk:e=",";break;case Km:e=".";break;case G7g:e=
hs?"X":"5";g=hs?!0:!1;l=hs?!1:!0;break;case F7g:k=!1,e="\\"}b.Ib[c]=f&&e?c8g(d,k,g,e,f):e?d8g(d,k,g,e,l):d}return b.Ib},BPh=function(b,c){for(var d=0;d<b.Na.length;d++)if(Oq(b.Na[d],c))return!0;return!1},NPh=function(b,c){switch(c){case WW:a:{if(c=b.Kt().Pba()){var d=c.getRange();if(d){var e=null;try{e=DVc(d,!0)}catch(f){}for(d=e&&e.node?e.node:d.FH();d&&d!=c.Fa();){if("FONT"==d.tagName&&d.getAttribute("face")||d.style&&d.style.fontFamily){c=!1;break a}d=d.parentNode}c=!0;break a}}c=!1}c&&GPh(b,b.wa,
"");break;case XW:case YW:case y7g:break;default:MPh(b,c,null)}};bY.prototype.qe=function(b){var c=this.Da.Jca;c=c.getAttribute(eh)||c.command;var d=this.Da.EN();MPh(this,c,d);b.stopPropagation()};
var MPh=function(b,c,d){var e=-1,f=b.Kt();if(f){switch(c){case rj:var g=Nxb;break;case UW:g=dyb;e=f.ha(c);b.ha++;break;case ZW:g=eyb;e=f.ha(c);b.ha++;break;case cX:g=fyb;e=f.ha(c);b.ha++;break;case WW:g=gyb;b.ha++;break;case XW:g=hyb;b.ha++;break;case YW:g=iyb;b.ha++;break;case y7g:g=jyb;b.ha++;break;case aX:g=kyb;break;case A7g:g=lyb;e=f.ha(c);b.ha++;break;case B7g:g=myb;e=f.ha(c);b.ha++;break;case bX:g=nyb;b.ha++;break;case z7g:g=oyb;b.ha++;break;case TW:g=pyb;b.ha++;break;case D7g:g=qyb;e=f.ha(c);
b.ha++;break;case C7g:g=ryb;e=f.ha(c);b.ha++;break;case H7g:g=byb;e=f.ha(c);b.ha++;break;case E7g:g=cyb;e=f.ha(c);b.ha++;break;case G7g:g=tyb;e=f.ha(c);b.ha++;break;case $W:g=syb;e=f.ha(c);b.ha++;break;case F7g:g=uyb;b.ha++;break;case Km:g=vyb;b.ha++;break;case sk:g=wyb;b.ha++;break;case VW:g=xyb}if(g){f=f.Pba();var k=!1;f&&f.getRange()&&(k=!f.getRange().isCollapsed());k=k?"S":"U";-1!=e&&(k+="-"+(e?"ON":"OFF"));e=b.Ob;f=g+"-"+k;k=[0,g,k];var l=e[f];l||(l=k);l[0]++;e[f]=l;e=b.hc;f=g;g=[0,g];(k=e[f])||
(k=g);k[0]++;e[f]=k}}b.dispatchEvent(new e8g(c,d))},HPh=function(b){return!!b&&0<b.xf()};
bY.prototype.qc=function(){if(this.isDisposed()||this.Ca)return!1;this.Ca=new v7g(void 0,void 0,this.Mb);this.wb(this.Ca);this.Ca.Tj(!1);this.Ca.qD=!1;this.Ca.n8a=!1;var b=this.Mb.$b("J-Z",this.Fa());this.Ca.Lc(b);cY(this,$W)&&(this.hb=OPh(this,zPh))&&(b=cY(this,$W),this.hb.Mk(b));cY(this,sk)&&this.Cb&&(this.kb=OPh(this,APh))&&(b=cY(this,sk),this.kb.Mk(b));KPh(this,WW,this.wa);KPh(this,XW,this.Aa);IPh(this);this.Wa.listen(this.Ca,Cf,this.Td);return!0};
var OPh=function(b,c){var d=new tO;b.wb(d);d.Aa=b.Ee;er(c,function(e,f){e=cY(b,f);nB(e,16,!1);d.Hg(e);b.Wa.listen(e,Cf,function(g){d.Mk(g.target)})},b);return d};bY.prototype.Ee=function(b,c){b&&(b.hh(c),IA(b.Fa(),"Oqc0n")&&b.setVisible(!c))};
bY.prototype.Td=function(b){if(this.Zc)this.Zc=!1;else{b=b.target;try{if(b instanceof $E){var c=b.$g().Pk;this.nb=c;var d=b.$g().value;MPh(this,c,d)}else if(b instanceof i8g){var e=b.Yb().Pk;this.nb=e;var f=b.Yb().value;MPh(this,e,f)}else{var g=b.Fa(),k=g.getAttribute(eh)||g.command;this.nb=k;"pcPlain"==k?this.getParent().Qea():NPh(this,k)}}finally{this.nb=null}}};var cY=function(b,c){return b.Ca?b.Ca.He(b.Zb(c)):null};
bY.prototype.yd=function(b){if(b=b.target.Hi())if(b=b.getAttribute(eh))b==sWf||b==YW?(b=cY(this,b))&&b.Ni(!0):NPh(this,b)};bY.prototype.vd=function(b){if(b=b.target.Hi().id){switch(b){case this.Zb(om):var c=D7g;break;case this.Zb(Eg):c=C7g;break;case this.Zb(Yj):c=$W;break;case this.Zb("i"):c=z7g;break;case this.Zb("o"):c=bX;break;case this.Zb("q"):c=TW}c&&NPh(this,c)}};
var IPh=function(b){if(!b.Ga){b.Ga=CPh(b);KPh(b,YW,b.Ga,12);b.getHandler().listen(b.Ga,hn,b.xe);var c=b.Ga.Fa();JA(c,"aAd");b.Ia=new mPh(ts(c),!0,b.Wb);b.wb(b.Ia);b.Ia.render(c);b.getHandler().listen(b.Ia,"Pg",b.De);b.Wb&&b.getHandler().listen(b.Ia,"Qg",b.he)}};
bY.prototype.xe=function(){var b=this.Kt()&&this.Kt().ha(YW);b=PPh(b);if(b="rgb(34, 34, 34)"==b||"#222"==b||"#222222"==b||"222"==b||"222222"==b?"rgb(0, 0, 0)":b){var c=this.Ia;c.Aa&&c.ha.HL(b)}b=this.Kt()&&this.Kt().ha(y7g);b=PPh(b);if(b=b==zza?"rgb(255, 255, 255)":b)c=this.Ia,c.Ba&&c.wa.HL(b)};var PPh=function(b){return typeof b!=ll?b:"rgb("+(b&255)+vb+((b&65280)>>8)+vb+((b&16711680)>>16)+")"};bY.prototype.De=function(b){this.Ga.setVisible(!1);MPh(this,YW,b.color)};
bY.prototype.he=function(b){this.Ga.setVisible(!1);MPh(this,y7g,b.color)};var QPh=function(b){b=b.Fa("r");var c=Ip.top.getComputedStyle(b);return b.offsetWidth-parseInt(c.width,10)+(parseInt(c.marginLeft,10)+parseInt(c.marginRight,10))};
bY.prototype.Pd=function(){var b=this.Fa("r");if(Ez(b)){a:{var c=this.Fa();var d=Az(c);for(c=Ts(c);c;c=Ts(c)){var e=Az(c);if(d.width!=e.width){d=e.width-QPh(this);break a}}d=500}if(d!=this.Ea){this.Ea=d;RPh(this,!0);b=b.lastChild.previousSibling;for(d=this.Ba.length-1;0<=d;d--)c=this.Ba[d].aba,Ns(c),Ks(this.Ba[d].aba,b),IA(c,q7g)?Dz(c,!0):IA(c,L7g)&&(c=c.getAttribute(eh),cY(this,c).HE(new hrb(null,c==YW?12:8,!1,!0)));this.Ba.length=0;Vy("u9",this.Kc,0,this);return}}SPh(this)};
bY.prototype.Kc=function(){var b=this.Fa("r").lastChild,c=b.previousSibling;qz(c).x<this.Ea?RPh(this,!1):TPh(this,b,c);SPh(this)};
bY.prototype.Sc=function(b,c){b&&!this.Ca&&this.qc();var d=this.Oa!=b;d&&(b&&(this.Fa("qp").style.left=Math.round(c-7)+fm,this.Db&&(UPh(this),Vy("v9",this.Pd,0,this))),Dz(this.Fa(),b),this.Oa=b);if(b){HPh(this.wa)||Vy("w9",this.$Fa,0,this);HPh(this.Aa)||Vy("x9",this.aGa,1,this);if(!this.Ha){this.Ha=CPh(this);KPh(this,sWf,this.Ha);var e=LPh(this),f=this.Af(vPh);c=yA(dPh,{id:f.Z1b,Mj:e[$W],css:"e4 aaA aaB",IP:t7g,Pk:$W});var g=yA(dPh,{id:f.kZb,Mj:e[C7g],css:"eP aaA aaB",IP:t7g,Pk:C7g});e=yA(dPh,{id:f.P5b,
Mj:e[D7g],css:"fc aaA aaB",IP:t7g,Pk:D7g});c=new jV([c,g,e]);c.setSize(1,3);JA(this.Ha.Fa(),"aUX");this.Ha.Xb(c,!0);JA(c.Fa(),"aAb");this.getHandler().listen(c,Cf,this.vd)}IPh(this);this.Db&&!this.Va&&(c=cY(this,WWf))&&((c=Bs("J-Z-M-I-JG",c.Fa()))&&Dz(c,!1),this.Va=CPh(this),JA(this.Va.Fa(),"aUX"),KPh(this,WWf,this.Va))}d&&this.dispatchEvent(b?"Mg":"Ng")};
var UPh=function(b){var c=b.Fa();c.style.visibility=Ui;c.style.overflow=Ui;c.style.width="0";b.Fa("dw").style.width="2000px"},SPh=function(b){var c=b.Fa();c.style.visibility=Mo;c.style.overflow="";c.style.width="";b.Fa("dw").style.width="";b.dispatchEvent("Og")},RPh=function(b,c){if(b=cY(b,WWf))b.setVisible(c),b=b.Fa().previousSibling,Dz(b,c)};bY.prototype.Ke=function(){this.Fc=!0};
var DPh=function(b,c,d){d=k8g[c]+" "+d+" aaA aaB";d={Pk:c,id:b.Zb(c),css:d,Mj:LPh(b)[c]};ir(xPh,c)&&c!=sWf&&c!=WWf&&!ir(yPh,c)?(d.IP="J-Z-aEu-I J-Z-I",b=b.Gb&&b.Cb?wPh:null,null!=b&&Oq(b,c)&&(d.IP+=" Oqc0n")):c==WW?(d.IP="J-Z-axO J-Z-M-I aOz",d.AK=!0,d.content=zMg):c==sWf||c==WWf||ir(yPh,c)?(d.IP=L7g,d.AK=!0):d.IP=t7g;return d};bY.prototype.Uc=np("Wb");
var VPh=function(b){for(var c=[],d=0;d<b.Ba.length;d++)b.Ba[d].wyb&&c.push(b.Ba[d].aba);b.Ka&&(b.Va.removeChild(b.Ka),b.Ka.dispose());b.Ka=new jV(c);b.Ka.setSize(1,c.length);b.Ka.listen(Cf,b.yd,!1,b);b.Va.Xb(b.Ka,!0);JA(b.Ka.Fa(),"aUW")},TPh=function(b,c,d){var e=Ip.top.getComputedStyle(d);e=b.Ea-c.offsetWidth-d.offsetWidth-parseInt(e.marginLeft,10)-parseInt(e.marginRight,10);for(var f=d.previousSibling;f;f=d){var g=0,k=!1;d=f.previousSibling;var l=IA(f,L7g);if(IA(f,t7g)||l){var n=qz(f);if(0!=n.x)if(g=
Az(f),g=n.x+g.width,g<e)break;else k=!0,l&&(l=new hrb(c,8,!1,!0),n=f.getAttribute(eh),cY(b,n).HE(l))}b.Ba.push({aba:f,Uk:g,wyb:k})}for(c=0;c<b.Ba.length;c++)Ns(b.Ba[c].aba);VPh(b)};
bY.prototype.Ed=function(b){if(this.Db){var c=this.Fa("r");if(Ez(this.Fa())&&Ez(c))if(c=this.Ea,this.Ea=b-QPh(this),!c)this.Kc();else if(c!=this.Ea)if(c<this.Ea)a:{if(0!=this.Ba.length){c=this.Fa("r").lastChild;b=c.previousSibling;c=this.Ea-Az(c).width-2-Az(b).width-4;for(var d=this.Ba.length-1;0<=d;d--){var e=this.Ba[d];if(e.Uk>=c&&(0!=d||e.Uk>=this.Ea)){VPh(this);break a}if(e.wyb)for(;this.Ba.length>d;)e=this.Ba.pop().aba,Ks(e,b)}RPh(this,!1)}}else UPh(this),b=this.Fa("r"),c=b.lastChild,d=c.previousSibling,
Az(b).width<this.Ea||(RPh(this,!0),TPh(this,c,d)),SPh(this)}};var WPh=function(b,c){var d=rOh(b,function(e){return e!=c&&1==e.childNodes.length});d|