nge-billing-project-dialog-project-header-text")+'"></span></div><div class="'+U("waffle-bigquery-change-billing-project-dialog-project-menu-wrapper")+'"></div></div>');return S(a)}
function YXh(){return S('<div class="'+U("waffle-bigquery-change-billing-project-dialog-footer-wrapper")+'"></div>')}function ZXh(a,b,c,d){iZ.call(this,"waffle-bigquery-change-billing-project-dialog",d);this.setTitle(this.oa().Ba("SPAN",void 0,"Change the billing project"));this.R=a;this.J=this.H=b;this.xa=c;this.D=new Zaf(void 0,this.oa());this.Ga(this.D);this.O=new BS("Cancel",this.oa());this.Ga(this.O);this.F=new YB("Update billing",this.oa());this.Ga(this.F);this.F.Na(!1)}t(ZXh,iZ);
ZXh.prototype.Ba=function(){iZ.prototype.Ba.call(this);iy(this.Jb(),XXh);this.oa().Je(this.Fa("waffle-bigquery-change-billing-project-dialog-project-header-text"),this.H);bZ(this).appendChild(ky(YXh));this.O.render(this.Fa("waffle-bigquery-change-billing-project-dialog-footer-wrapper"));this.F.render(this.Fa("waffle-bigquery-change-billing-project-dialog-footer-wrapper"));this.D.render(this.bb("waffle-bigquery-change-billing-project-dialog-project-menu-wrapper"));MX(this.D).setAttribute("placeholder",
"Search projects");this.oa().Gi(this.D.Ka(),!1)};ZXh.prototype.Ha=function(){iZ.prototype.Ha.call(this);0<this.R.length&&$Xh(this,this.R);this.getHandler().listen(this.O,"action",this.reject).listen(this.F,"action",this.ma).listen(this.D,"change",this.V)};function $Xh(a,b){var c;b=Uc(b,function(d){var e=new gZ(d.getId(),d.getName());d.getId()===a.H&&(c=e);return e});abf(a.D,b);bbf(a.D);c&&OWh(a.D,c);fbf(a.D)}
ZXh.prototype.V=function(){var a=this.D.bf();if(a){var b=a.Sa();this.J=b instanceof Oaf?b.getValue():a.Sa().$h();this.F.Na(this.H!=this.J)}};ZXh.prototype.ma=function(){var a=this;this.D.Mn(!0);LWh(this.xa,this.J).then(function(){a.isDisposed()||(a.D.Mn(!1),a.resolve(a.J))},function(){a.isDisposed()||(a.D.Mn(!1),rA.getInstance().postMessage(tA("Unable to connect to this billing project","error",!0,3E3)))})};function aYh(a){Wn.call(this,"Gf");this.C=a}t(aYh,Wn);
function bYh(a,b,c,d,e){aZ.call(this,"waffle-bigquerydbsourceediterror",e);this.J=c;this.L=a;this.O=b;this.D=d;this.F=new BS("Cancel");this.Ga(this.F);this.H=new YB("Select new table",this.oa());this.Ga(this.H);this.setTitle(this.oa().Ba("SPAN",void 0,cYh(this)))}t(bYh,aZ);
bYh.prototype.Ba=function(){var a=this;aZ.prototype.Ba.call(this);a:switch(this.D){case "no-table":var b="The following data connected to this sheet can no longer be found on BigQuery.";break a;case "access-denied":b="You do not have access to the following data connected to this sheet.";break a;default:throw Error("Unsupported error: "+this.D);}this.Jb().appendChild(this.oa().Ba("DIV","waffle-bigquerydbsourceediterror-error-text",b));b=C(this.J.C,3);b=C(b,4);this.Ga(new VXh(this.L,this.O,b,this.oa()),
!0);b=bZ(this);this.H.render(b);this.F.render(b);this.getHandler().listen(this.F,"action",function(){return void a.qE()}).listen(this.H,"action",function(){Ipb.Cb(new hbf(a.J.Of(),"pick-new source"))})};function cYh(a){switch(a.D){case "no-table":return"Data not found";case "access-denied":return"Access denied";default:throw Error("Unsupported error: "+a.D);}}function dYh(){Q.apply(this,arguments)}t(dYh,Q);
dYh.prototype.Ba=function(){var a=this.oa().Ba("DIV",{"class":"waffle-dataconnector-tablepicker-multilevelmenu-container"});this.jb(a)};function eYh(a,b){return Uc(a,function(c){return new MWh(c,b)})}function fYh(a,b,c){return Uc(a,function(d){return new NWh(d.getName(),c,b,d.getType())})}function gYh(a){Wn.call(this,"Hf");this.Pa=a}t(gYh,Wn);function hYh(a,b){Q.call(this,b);this.H=a;this.C=new dYh(this.oa());this.Ga(this.C,!0);this.D=0}t(hYh,Q);
hYh.prototype.Ba=function(){Q.prototype.Ba.call(this);qx(this.getElement(),"waffle-dataconnector-tablepicker-multilevelmenu")};hYh.p