=this.Aa||"a"==this.Aa)&&(b=this.whb(this.Da()),iuh(this.Ea,b));this.Su=this.Zr=-1};
v.l3c=function(){var b=this,c=this.Da();this.hc=c?"Rich text":dph;3!=this.Sb&&txh(this,this.hc);c?(this.Ka||this.vk())&&jwh(this.Fc,!0):jwh(this.Fc,!1);this.Mc.zf()||this.getHandler().Bd(this.Mc,"Zd",function(){var d=b.Mc;d.Aa=null;ds||d.focus();if(d=d.ha)d.H9a(),d.Om()&&d.focus()})};
v.mYc=function(){var b=this;(this.Ka||this.vk()&&!this.Sc)&&Vy("Yba",function(){jwh(b.Fc,b.Da())},0,this);if(this.Ea.wa&&this.Mc.wa()){var c=Bs("gmail_extra",this.Mc.ha.Fa());c&&(Ns(c),this.xh())}this.Mc.wa()&&(c=this.Mc.ha.Fa())&&Kqh(c);c=Qxh(this);this.Dc=new Wvh(this.Ua(),c);this.wb(this.Dc);this.Dc.Ca=this.cE()?-2:Wwh(this)?-1:0;this.Fa("dts").appendChild(this.Dc.Fa());this.Ff(this.Dc)};
v.Gdb=function(b){var c=this.Mc.ha;if(c&&c.Fa()){var d=c.Fa().scrollHeight,e=c.Fa().scrollWidth;yqh(b)||d!=this.Zr||e!=this.Su?(this.eJ(b),this.Zr=d,this.Su=e):EX(b,"Ua")&&!Bqh(b)&&(b=Date.now(),250<b-this.ugb&&(this.ugb=b,c.Om()?Vy("Zba",tq(this.Bw,!0),0,this):this.Bw(!0)))}else this.Su=this.Zr=-1};
v.eDb=function(b){if(!duh(this.jg)){var c=b.charCode||b.keyCode;if((40==c||39==c)&&!b.shiftKey){c=!1;if(this.vL){var d=this.Mc.ha.getRange(),e=this.vL;!e||!d||e.Mh()!=d.Mh()||e.ik()!=d.ik()||e.Ri()!=d.Ri()||e.Qk()!=d.Qk()||d.Ri().nodeType==Node.TEXT_NODE&&d.Qk()<d.Ri().nodeValue.length||(c=!0,this.lD.dispatchEvent(jn))}b.type!=Qj||c?this.vL=null:this.vL=this.Mc.ha.getRange()}}};v.Bv=function(){this.N2++;Vy("$ba",this.Tld,0,this)};v.Tld=function(){0==--this.N2&&this.eJ()};
v.eJ=function(b){if(this.isVisible())if(this.A2)this.Bv();else{this.A2=!0;try{if(!this.isDisposed()&&!this.Se&&this.Mc.ha&&(jxh(this),Rxh(this,b),!(0<this.N2)||EX(b,Um)||EX(b,"Mg")||EX(b,"Ng"))){if(this.Kl){var c=this.Mc.ha.Fa();if(c){var d=c.scrollWidth,e=c.scrollHeight;d==this.Kl.scrollWidth&&e==this.Kl.scrollHeight||zz(this.Kl,d,e)}}if(IX(this))bth(this,b);else{var f=this.Fa("srt");if(f){var g=f.offsetHeight-100,k=this.Fa(iX),l=this.Fa("fph"),n=Rxh(this,b);yz(l,n);var q=IA(this.Fa(iX),"aDi");if(!q&&
EX(b,"Mg")){var u=this.Ga.G_(k);this.Ga.aD(Math.round(u+40),k)}else if(!q&&EX(b,"Ng")){var w=this.Ga.G_(k);this.Ga.aD(Math.round(w+-40),k)}c=!1;if(0<g){var E=this.Fa(ei),G=Bz(E),T;g=!1;var fa=this.Fa(sph),qa=Mxh(this),za=G.top-qa-7-fa.offsetHeight;if(!Sxh(this)&&0>=za){var Ja=za+G.height;100<=Ja?(Txh(this,2,qa+7),g=!0):(G=Ja-100,G>-fa.offsetHeight-7&&(Txh(this,3,-za+G),g=!0))}(T=g)||Txh(this,1);fa=!1;var Sa=this.Fa(iX),bb=parseInt(window.getComputedStyle(Sa).height,10),ib=bxh(this),ab=ib.top+ib.height+
bb,Eb=IA(Sa,"aDi"),Jb=this.Td.zd().height;za=Jb-35;if(ib.top<Jb-100&&ab>=za){var hc=Bz(this.Fa(sph)),Sc=hc.top+hc.height+bb+100;Uxh(this);JA(Sa,"aDi");if(0>=za-Sc){var oe=Math.round(ab-Sc);Sa.style.position=yf;Sa.style.bottom=oe+fm;Sa.style.left="-0px";Sa.style.right="-0px";this.cC=!1}else{var vd=this.Fa("sap"),Uc=Vxh(this,vd);Sa.style.position=pi;Sa.style.left=Uc+fm;Sa.style.width=Math.round(vd.offsetWidth)+fm;ib=gg;var Rd=Wxh(this);if(Rd){var nf=Xxh(this,Rd,"sta"),Ad=Rd.clientHeight<Rd.scrollHeight;
if(0<nf||Ad){var Uf=Bz(this.Fa(iX)),Bf=this.Td.zd().height-Uf.top;ib="rect(-500px,"+(Rd.clientWidth+nf)+"px,"+Bf+"px,"+nf+IPf}}var kd=ib;kd!=gg&&(Sa.style.clip=kd);!this.cC&&this.qK&&this.Cb.Kb(iEb);this.cC=!0}!Eb&&this.qK&&this.cC&&this.Cb.Kb(iEb);JA(Sa,"aDi");fa=!0}var Sd=this.Fa("sam"),Je=this.Fa("spm");Eb=!1;if(fa){var Hf=this.Td.zd().height,tg=this.Ga.wa(this.Fa()),Ce=Mxh(this)+tg.clientHeight;var qf=Hf-Ce;var cg=0<Math.round(qf),Zi=ab-tz(Sa)-bb;!this.qK&&cg&&this.cC&&this.Cb.Kb(iEb);(this.qK=
cg)?(yz(Sd,Math.max(0,Math.min(Zi+5-1,35-qf-1))),Eb=!0):(yz(Sd,5+Math.min(Zi,35)),Eb=ds&&35>Zi);Eb&&yz(Je,Math.round(Zi+35))}Dz(Sd,fa);Dz(Je,fa&&Eb);c=fa;if(!this.kb&&(c||T)&&Cqh(b)){var Xe=EX(b,"Mg");this.Bw(yqh(b)||Xe)}}else Txh(this,1);c||Pxh(this,!1)}}EX(b,Um)&&(this.Zg.yp(),this.Mf.yp(),this.Eb.yp());var ii=this.Mc.ha.Fa();ii&&(this.pY=ii.scrollHeight);if(this.Sc){var Aj=this.Fa().scrollHeight;this.qY!=Aj&&(this.qY=Aj,this.dispatchEvent("zg"))}this.Dc&&this.Dc.update()}}finally{this.A2=!1}}};
v.WDb=function(){return!!duh(this.jg)};
var bxh=function(b){b=Bz(b.Fa(ei));--b.top;b.height+=2;return b},Uxh=function(b){b=b.Fa(iX);b.style.bottom="";b.style.clip="";b.style.left="";b.style.position="";b.style.right="";b.style.top="";b.style.width=""},Vxh=function(b,c){var d=b.Ga.wa(c);b=b.Ga.CVa(d);return rz(c).x-b},Pxh=function(b,c){var d=b.Fa(iX);if(c){c=rz(d);var e=Az(d);if(IX(b)){var f=1;if(b.Ka){var g=b.Qa().$b("aSt"),k=tz(g);g=g.clientHeight;b=b.Td.zd().height;f+=b-g-k}d.style.bottom=f+hm}else d.style.top=c.y+hm;d.style.left=c.x+
fm;d.style.width=e.width+fm;JA(d,"aDi")}else LA(d,"aDi"),Uxh(b)},Xxh=function(b,c,d){b=b.Fa(d);return rz(c).x-rz(b).x},Wxh=function(b){if(IX(b))return null;if(Yxh(b)){var c=b.Eb.Ptb();c||(c=b.Qa().IU(b.Fa(),"apN"));if(c)return c}return b.Qa().$b(b.Sc?"iC":"Tm")},Yxh=function(b){b=b.Ua().Wc(UC);return!(!b||!b.Ac())},Sxh=function(b){if(!b.kb)return!1;var c=b.Fa(sph),d=Mxh(b);return 150>b.Td.zd().height-d-7-c.offsetHeight},Txh=function(b,c,d){if(!IX(b)){var e=b.Fa(sph),f=b.Fa("rap"),g=b.Fa("ram");Zxh(b,
e,f,c,d);$xh(b,c);var k=1!=c;NA(e,"azY",k);e=e.style;if(k){var l=gg;if(f=Wxh(b)){var n=Xxh(b,f,"rap"),q=f.clientHeight<f.scrollHeight;if(0<n||q)l=b.Td.zd().height,l="rect(-20px,"+(f.clientWidth+n)+"px,"+l+"px,"+n+IPf}f=l}else f=gg;e.clip=f;Dz(g,k);b.oY=c;e=b.Fa("spw");f=b.Fa("spp");Zxh(b,e,f,c,d);NA(e,"azy",k);c=e.style;if(k){k=gg;if(d=Wxh(b))b=Xxh(b,d,"spp"),0<b&&(k="rect(0px,100px,100px,"+b+IPf);b=k}else b=gg;c.clip=b}},Zxh=function(b,c,d,e,f){f="top: "+Math.round(f||0)+hm;2==e?(b=Vxh(b,d),c.style.cssText=
"left: "+Math.round(b)+"px; width: "+Math.round(d.offsetWidth)+"px; "+f):3==e?(d=Az(c),c.style.cssText="position: relative; width: "+Math.round(d.width)+"px; "+f):c.style.cssText="position: static;"},$xh=function(b,c){if(!IX(b)){var d=b.Fa("rap");2==c?(b=b.Fa(sph),yz(d,b.offsetHeight)):yz(d,0)}};JX.prototype.Q8b=function(){if(!IX(this)&&this.kb&&Sxh(this)){var b=this.Fa("rap");this.Ga.scrollIntoView(b,2,!0,2);Txh(this,1)}};JX.prototype.hY=function(b){this.Dha.add(b)};
var Mxh=function(b){var c=b.XH()?75:126;c+=Nxh(b);c+=b.Eb.wmb()||0;if(b.Sc)return 49;var d=0;if(Wwh(b)){var e=b.Ua().get(Qy).Qa().$b("M9");d=c}else b.cE()?(e=b.Ua().get(Qy).Qa().$b("AO"),Yxh(b)&&(b=b.Ua().get(My).Je())&&b.Ue()==JF&&(b=b.i5())&&(d+=b.offsetHeight)):e=Wxh(b);return e?Math.round(d+Math.max(0,tz(e))):c},Rxh=function(b,c){if(EX(c,"Mg")||EX(c,Rl))b.Tu=40;else if(EX(c,"Ng")||EX(c,"qi"))b.Tu=0;return 0==b.Tu&&b.Dc?b.Dc.Jd():b.Tu};
JX.prototype.Bw=function(b){if(!this.isDisposed()){var c=this.Mc.ha,d=c.Fa().scrollHeight;if(IX(this)||b||d>this.pY||d!=this.Zr){a:{d=c.getRange();b=c.Wk;if(d&&zqh(d)){var e=w8b(OI(d),!1);if(e){b=e.y;break a}if(d=Aqh(d,b)){e=tz(d)+d.offsetHeight;b.removeNode(d);b=e;break a}}b=null}b&&(c.Om()&&(c=Bs("Am",this.Fa()))&&(b+=tz(c)),this.Ot(b))}}};
JX.prototype.Ot=function(b,c){c=b+(void 0===c?0:c);var d=this.Fa(iX),e=Rxh(this);c=tz(d)-e-c-6;if(fs||Wwh(this))c-=IX(this)?gs||!this.Dc?0:this.Dc.Jd():0;0>c&&ayh(this,c+(ds?0:1));if(IX(this)?0:IA(this.Fa(sph),"azY"))c=Bz(this.Fa(sph)),b=c.top+c.height+30-b,0<b&&ayh(this,b)};var ayh=function(b,c){if(IX(b))b=b.Fa(ei),b.scrollTop=Math.round(b.scrollTop-c);else{var d=b.Fa(iX),e=b.Ga.G_(d);Vy("aca",tq(b.Ga.aD,Math.round(e-c),d),0,b.Ga)}};JX.prototype.onMinimized=function(){uuh(this);this.dispatchEvent("Eb")};
var uuh=function(b){var c=b.Mc.ha,d=c?c.getRange():null;b.OP=zqh(d)?d:null;if(b.OP)for(d=d.Mh(),c=c.Fa(),b.Tt=[];d!==c;)for(var e=d.parentNode.childNodes,f=0;f<e.length;f++)if(e[f]===d){b.Tt.push(f);d=d.parentNode;break}};
JX.prototype.V_=function(){if(this.OP){var b=this.Mc.ha,c=this.OP,d=null;if(Us(b.Fa(),c.Mh()))d=c.Mh();else if(0<this.Tt.length){d=b.Fa();for(var e=this.Tt.length-1;0<=e;e--)if(d&&d.childNodes)d=d.childNodes[this.Tt[e]];else{d=null;break}}d&&(QI(d,c.ik()).select(),b.focus());this.Tt=[]}};JX.prototype.GKa=function(){if(IX(this))this.gM=this.Fa(ei).scrollTop;else{var b=this.Fa(iX);this.gM=this.Ga.G_(b)}};
JX.prototype.W$a=function(){if(IX(this))this.Fa(ei).scrollTop=this.gM;else{