
	</enum>
	<enum id="EGFSmoothMode">
		<metadata type="enum">
			<enum xtmlvalue="Default" value="0" />
			<enum xtmlvalue="Quick" value="1" />
			<enum xtmlvalue="Bilinear" value="2" />
			<enum xtmlvalue="Bicubic" value="3" />
		</metadata>
	</enum>
	<enum id="GifStretchMode">
		<metadata type="enum">
			<enum xtmlvalue="Center" value="0" />
			<enum xtmlvalue="Adjust" value="1" />
			<enum xtmlvalue="Stretch" value="2" />
		</metadata>
	</enum>
	<interface iid="A1767715-E4D9-464d-B62A-57142C58B9EE" label="Element" id="IGFElement" inherit="IDispatch">
		<prop field="name" type="BSTR" group="常用"  toolTips="BSTR:控件的名称，可以用来在函数Util::GF::GetElementByName和IGFElement的GetElementByName"/>
		<prop field="config" type="BSTR" group="常用" toolTips="BSTR:控件的风格"/>
		<prop field="itemData" type="ITXData" toolTips="ITXData:额外数据存储。用于附带额外的属性，比如 ToolbarItem的strSortKey排序参数，一般由存，取双方协商决定"/>
	</interface>
	<interface iid="2F2DF1A2-2037-4116-B7A1-D38F87741CA2" label="ConfigAgent" id="IGFConfigAgent" inherit="IGFElement">
		<prop field="configType" type="BSTR" />
		<prop field="comboConfig" type="BSTR" />
		<prop field="configProp" type="configprop" />
		<prop field="configEffect" type="configeffect" />
	</interface>
	<interface iid="A75AA927-727A-4f97-85EF-71565B3D6840" id="IGFDraw" inherit="IGFElement">
		<prop field="hidden" type="BOOL" />
		<prop field="alpha" type="BYTE" />
		<prop field="colorize" type="BOOL" />
	</interface>
	<interface iid="84B1812A-F064-453b-B48D-5B61399DAE45" id="IGFEffect" inherit="IGFElement" />
	<interface iid="208308FE-CD22-4420-BF71-80396E326181" label="Font" id="IGFFont" inherit="IGFElement">
		<prop field="height" type="double" toolTips="double:字体的高度。详见MSDN函数CreateFont中的参数nHeight解释。默认为9"/>
		<prop field="width" type="double" toolTips="double:字体的宽度。详见MSDN函数CreateFont中的参数nWidth解释。默认为0" />
		<prop field="orientation" type="int" toolTips="int:字体的方向。详见MSDN函数CreateFont中的参数nOrientation解释。默认为0" />
		<prop field="weight" type="int" toolTips="int:字